version: '3.8'

services:
  django:
    image: ghcr.io/cskerritt/skerritt-economics-django:latest
    container_name: skerritt_django
    restart: always
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - db_volume:/app/db
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=skerritt_site.settings_production
      - DJANGO_ALLOWED_HOSTS=skerritteconomics.com,www.skerritteconomics.com,localhost
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_DEBUG=False
    env_file:
      - .env
    networks:
      - skerritt_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  caddy:
    image: caddy:2-alpine
    container_name: skerritt_caddy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - static_volume:/srv/static:ro
      - media_volume:/srv/media:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - django
    networks:
      - skerritt_network

volumes:
  static_volume:
  media_volume:
  caddy_data:
  caddy_config:
  db_volume:

networks:
  skerritt_network:
    driver: bridge