# Northeast US Cities Database - Top 20 Cities/Towns by State
# Based on 2020 Census data and geographic coordinates
# States: NY, PA, MA, CT, RI, NJ, VT, NH, ME, MD, DE, WV

NORTHEAST_CITIES = {
    # NEW YORK
    "new-york-city": {
        "name": "New York City",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Multiple Counties",
        "population": 8804190,
        "lat": 40.730610,
        "lng": -73.935242,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Mid-Atlantic"
    },
    "buffalo": {
        "name": "Buffalo",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Erie County",
        "population": 278349,
        "lat": 42.8864,
        "lng": -78.8784,
        "metro_area": "Buffalo-Cheektowaga-Niagara Falls",
        "region": "Upstate New York"
    },
    "yonkers": {
        "name": "Yonkers",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Westchester County",
        "population": 211569,
        "lat": 40.9312,
        "lng": -73.8988,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Downstate New York"
    },
    "rochester-ny": {
        "name": "Rochester",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Monroe County",
        "population": 211328,
        "lat": 43.1566,
        "lng": -77.6088,
        "metro_area": "Rochester",
        "region": "Upstate New York"
    },
    "syracuse": {
        "name": "Syracuse",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Onondaga County",
        "population": 148620,
        "lat": 43.0481,
        "lng": -76.1474,
        "metro_area": "Syracuse",
        "region": "Upstate New York"
    },
    "albany": {
        "name": "Albany",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Albany County",
        "population": 99224,
        "lat": 42.6803,
        "lng": -73.8370,
        "metro_area": "Albany-Schenectady-Troy",
        "region": "Capital District"
    },
    "new-rochelle": {
        "name": "New Rochelle",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Westchester County",
        "population": 79726,
        "lat": 40.9115,
        "lng": -73.7823,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Downstate New York"
    },
    "mount-vernon-ny": {
        "name": "Mount Vernon",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Westchester County",
        "population": 73893,
        "lat": 40.9126,
        "lng": -73.8307,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Downstate New York"
    },
    "schenectady": {
        "name": "Schenectady",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Schenectady County",
        "population": 67047,
        "lat": 42.8142,
        "lng": -73.9396,
        "metro_area": "Albany-Schenectady-Troy",
        "region": "Capital District"
    },
    "utica": {
        "name": "Utica",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Oneida County",
        "population": 65283,
        "lat": 43.1009,
        "lng": -75.2327,
        "metro_area": "Utica-Rome",
        "region": "Central New York"
    },
    "white-plains": {
        "name": "White Plains",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Westchester County",
        "population": 59559,
        "lat": 41.0340,
        "lng": -73.7629,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Downstate New York"
    },
    "niagara-falls-ny": {
        "name": "Niagara Falls",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Niagara County",
        "population": 48671,
        "lat": 43.0962,
        "lng": -79.0377,
        "metro_area": "Buffalo-Cheektowaga-Niagara Falls",
        "region": "Western New York"
    },
    "troy": {
        "name": "Troy",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Rensselaer County",
        "population": 46787,
        "lat": 42.7284,
        "lng": -73.6918,
        "metro_area": "Albany-Schenectady-Troy",
        "region": "Capital District"
    },
    "binghamton": {
        "name": "Binghamton",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Broome County",
        "population": 47969,
        "lat": 42.0987,
        "lng": -75.9180,
        "metro_area": "Binghamton",
        "region": "Southern Tier"
    },
    "rome-ny": {
        "name": "Rome",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Oneida County",
        "population": 32127,
        "lat": 43.2128,
        "lng": -75.4557,
        "metro_area": "Utica-Rome",
        "region": "Central New York"
    },
    "elmira": {
        "name": "Elmira",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Chemung County",
        "population": 26523,
        "lat": 42.0898,
        "lng": -76.8077,
        "metro_area": "Elmira",
        "region": "Southern Tier"
    },
    "jamestown-ny": {
        "name": "Jamestown",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Chautauqua County",
        "population": 28712,
        "lat": 42.0970,
        "lng": -79.2353,
        "metro_area": "Jamestown-Dunkirk-Fredonia",
        "region": "Western New York"
    },
    "watertown-ny": {
        "name": "Watertown",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Jefferson County",
        "population": 24685,
        "lat": 43.9748,
        "lng": -75.9107,
        "metro_area": "Watertown-Fort Drum",
        "region": "North Country"
    },
    "ithaca": {
        "name": "Ithaca",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Tompkins County",
        "population": 32108,
        "lat": 42.4430,
        "lng": -76.5019,
        "metro_area": "Ithaca",
        "region": "Finger Lakes"
    },
    "poughkeepsie": {
        "name": "Poughkeepsie",
        "state": "New York",
        "state_abbr": "NY",
        "county": "Dutchess County",
        "population": 31554,
        "lat": 41.7004,
        "lng": -73.9209,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Hudson Valley"
    },

    # PENNSYLVANIA
    "philadelphia": {
        "name": "Philadelphia",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Philadelphia County",
        "population": 1603797,
        "lat": 39.9526,
        "lng": -75.1652,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Southeast"
    },
    "pittsburgh": {
        "name": "Pittsburgh",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Allegheny County",
        "population": 302971,
        "lat": 40.4406,
        "lng": -79.9959,
        "metro_area": "Pittsburgh",
        "region": "Southwest"
    },
    "allentown": {
        "name": "Allentown",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Lehigh County",
        "population": 125845,
        "lat": 40.6084,
        "lng": -75.4902,
        "metro_area": "Allentown-Bethlehem-Easton",
        "region": "Lehigh Valley"
    },
    "reading": {
        "name": "Reading",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Berks County",
        "population": 95112,
        "lat": 40.3356,
        "lng": -75.9269,
        "metro_area": "Reading",
        "region": "Southeast"
    },
    "erie": {
        "name": "Erie",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Erie County",
        "population": 94831,
        "lat": 42.1292,
        "lng": -80.0851,
        "metro_area": "Erie",
        "region": "Northwest"
    },
    "scranton": {
        "name": "Scranton",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Lackawanna County",
        "population": 76328,
        "lat": 41.4090,
        "lng": -75.6624,
        "metro_area": "Scranton--Wilkes-Barre",
        "region": "Northeast"
    },
    "bethlehem": {
        "name": "Bethlehem",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Northampton County",
        "population": 75781,
        "lat": 40.6259,
        "lng": -75.3705,
        "metro_area": "Allentown-Bethlehem-Easton",
        "region": "Lehigh Valley"
    },
    "lancaster": {
        "name": "Lancaster",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Lancaster County",
        "population": 58039,
        "lat": 40.0379,
        "lng": -76.3055,
        "metro_area": "Lancaster",
        "region": "South Central"
    },
    "harrisburg": {
        "name": "Harrisburg",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Dauphin County",
        "population": 50099,
        "lat": 40.2732,
        "lng": -76.8839,
        "metro_area": "Harrisburg-Carlisle",
        "region": "South Central"
    },
    "york": {
        "name": "York",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "York County",
        "population": 44800,
        "lat": 39.9626,
        "lng": -76.7277,
        "metro_area": "York-Hanover",
        "region": "South Central"
    },
    "wilkes-barre": {
        "name": "Wilkes-Barre",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Luzerne County",
        "population": 44328,
        "lat": 41.2459,
        "lng": -75.8813,
        "metro_area": "Scranton--Wilkes-Barre",
        "region": "Northeast"
    },
    "chester": {
        "name": "Chester",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Delaware County",
        "population": 32605,
        "lat": 39.8496,
        "lng": -75.3557,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Southeast"
    },
    "norristown": {
        "name": "Norristown",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Montgomery County",
        "population": 35748,
        "lat": 40.1215,
        "lng": -75.3396,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Southeast"
    },
    "johnstown": {
        "name": "Johnstown",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Cambria County",
        "population": 18411,
        "lat": 40.3267,
        "lng": -78.9220,
        "metro_area": "Johnstown",
        "region": "Southwest"
    },
    "altoona": {
        "name": "Altoona",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Blair County",
        "population": 43963,
        "lat": 40.5187,
        "lng": -78.3947,
        "metro_area": "Altoona",
        "region": "Central"
    },
    "easton": {
        "name": "Easton",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Northampton County",
        "population": 28127,
        "lat": 40.6884,
        "lng": -75.2077,
        "metro_area": "Allentown-Bethlehem-Easton",
        "region": "Lehigh Valley"
    },
    "mckeesport": {
        "name": "McKeesport",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Allegheny County",
        "population": 17727,
        "lat": 40.3476,
        "lng": -79.8645,
        "metro_area": "Pittsburgh",
        "region": "Southwest"
    },
    "williamsport": {
        "name": "Williamsport",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Lycoming County",
        "population": 27754,
        "lat": 41.2412,
        "lng": -77.0011,
        "metro_area": "Williamsport",
        "region": "North Central"
    },
    "hazleton": {
        "name": "Hazleton",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Luzerne County",
        "population": 25703,
        "lat": 40.9584,
        "lng": -75.9746,
        "metro_area": "Hazleton",
        "region": "Northeast"
    },
    "new-castle": {
        "name": "New Castle",
        "state": "Pennsylvania",
        "state_abbr": "PA",
        "county": "Lawrence County",
        "population": 21926,
        "lat": 40.9979,
        "lng": -80.3473,
        "metro_area": "New Castle",
        "region": "Northwest"
    },

    # MASSACHUSETTS
    "boston": {
        "name": "Boston",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Suffolk County",
        "population": 675647,
        "lat": 42.3601,
        "lng": -71.0589,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "New England"
    },
    "worcester": {
        "name": "Worcester",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Worcester County",
        "population": 206518,
        "lat": 42.2626,
        "lng": -71.8023,
        "metro_area": "Worcester",
        "region": "Central Massachusetts"
    },
    "springfield-ma": {
        "name": "Springfield",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Hampden County",
        "population": 155929,
        "lat": 42.1015,
        "lng": -72.5898,
        "metro_area": "Springfield",
        "region": "Western Massachusetts"
    },
    "cambridge": {
        "name": "Cambridge",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Middlesex County",
        "population": 118403,
        "lat": 42.3736,
        "lng": -71.1097,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Greater Boston"
    },
    "lowell": {
        "name": "Lowell",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Middlesex County",
        "population": 115554,
        "lat": 42.6334,
        "lng": -71.3162,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Greater Boston"
    },
    "brockton": {
        "name": "Brockton",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Plymouth County",
        "population": 105643,
        "lat": 42.0834,
        "lng": -71.0184,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Greater Boston"
    },
    "new-bedford": {
        "name": "New Bedford",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Bristol County",
        "population": 101079,
        "lat": 41.6362,
        "lng": -70.9342,
        "metro_area": "New Bedford",
        "region": "South Coast"
    },
    "quincy": {
        "name": "Quincy",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Norfolk County",
        "population": 101636,
        "lat": 42.2529,
        "lng": -71.0023,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Greater Boston"
    },
    "lynn": {
        "name": "Lynn",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Essex County",
        "population": 101253,
        "lat": 42.4668,
        "lng": -70.9495,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "North Shore"
    },
    "fall-river": {
        "name": "Fall River",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Bristol County",
        "population": 94000,
        "lat": 41.7015,
        "lng": -71.1550,
        "metro_area": "Providence-Warwick",
        "region": "South Coast"
    },
    "newton": {
        "name": "Newton",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Middlesex County",
        "population": 88923,
        "lat": 42.3370,
        "lng": -71.2092,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Greater Boston"
    },
    "lawrence": {
        "name": "Lawrence",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Essex County",
        "population": 89143,
        "lat": 42.7070,
        "lng": -71.1631,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Merrimack Valley"
    },
    "somerville": {
        "name": "Somerville",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Middlesex County",
        "population": 81045,
        "lat": 42.3876,
        "lng": -71.0995,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Greater Boston"
    },
    "framingham": {
        "name": "Framingham",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Middlesex County",
        "population": 72362,
        "lat": 42.2793,
        "lng": -71.4162,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "MetroWest"
    },
    "haverhill": {
        "name": "Haverhill",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Essex County",
        "population": 67787,
        "lat": 42.7762,
        "lng": -71.0773,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Merrimack Valley"
    },
    "waltham": {
        "name": "Waltham",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Middlesex County",
        "population": 65218,
        "lat": 42.3765,
        "lng": -71.2356,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Greater Boston"
    },
    "malden": {
        "name": "Malden",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Middlesex County",
        "population": 66263,
        "lat": 42.4251,
        "lng": -71.0662,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Greater Boston"
    },
    "medford": {
        "name": "Medford",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Middlesex County",
        "population": 59659,
        "lat": 42.4184,
        "lng": -71.1061,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "Greater Boston"
    },
    "taunton": {
        "name": "Taunton",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Bristol County",
        "population": 59408,
        "lat": 41.9001,
        "lng": -71.0903,
        "metro_area": "Boston-Cambridge-Newton",
        "region": "South Shore"
    },
    "chicopee": {
        "name": "Chicopee",
        "state": "Massachusetts",
        "state_abbr": "MA",
        "county": "Hampden County",
        "population": 55560,
        "lat": 42.1487,
        "lng": -72.6078,
        "metro_area": "Springfield",
        "region": "Western Massachusetts"
    },

    # CONNECTICUT
    "bridgeport": {
        "name": "Bridgeport",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Fairfield County",
        "population": 148654,
        "lat": 41.1865,
        "lng": -73.1952,
        "metro_area": "Bridgeport-Stamford-Norwalk",
        "region": "Southwest Connecticut"
    },
    "stamford": {
        "name": "Stamford",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Fairfield County",
        "population": 135470,
        "lat": 41.0534,
        "lng": -73.5387,
        "metro_area": "Bridgeport-Stamford-Norwalk",
        "region": "Southwest Connecticut"
    },
    "new-haven": {
        "name": "New Haven",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "New Haven County",
        "population": 134023,
        "lat": 41.3083,
        "lng": -72.9279,
        "metro_area": "New Haven-Milford",
        "region": "South Central Connecticut"
    },
    "hartford": {
        "name": "Hartford",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Hartford County",
        "population": 121054,
        "lat": 41.7658,
        "lng": -72.6734,
        "metro_area": "Hartford-West Hartford-East Hartford",
        "region": "North Central Connecticut"
    },
    "waterbury": {
        "name": "Waterbury",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "New Haven County",
        "population": 114403,
        "lat": 41.5581,
        "lng": -73.0515,
        "metro_area": "Waterbury",
        "region": "Central Connecticut"
    },
    "norwalk": {
        "name": "Norwalk",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Fairfield County",
        "population": 91184,
        "lat": 41.1175,
        "lng": -73.4079,
        "metro_area": "Bridgeport-Stamford-Norwalk",
        "region": "Southwest Connecticut"
    },
    "danbury": {
        "name": "Danbury",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Fairfield County",
        "population": 86518,
        "lat": 41.3948,
        "lng": -73.4540,
        "metro_area": "Danbury",
        "region": "Western Connecticut"
    },
    "new-britain": {
        "name": "New Britain",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Hartford County",
        "population": 74135,
        "lat": 41.6612,
        "lng": -72.7795,
        "metro_area": "Hartford-West Hartford-East Hartford",
        "region": "Central Connecticut"
    },
    "west-hartford": {
        "name": "West Hartford",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Hartford County",
        "population": 64083,
        "lat": 41.7620,
        "lng": -72.7420,
        "metro_area": "Hartford-West Hartford-East Hartford",
        "region": "Central Connecticut"
    },
    "greenwich": {
        "name": "Greenwich",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Fairfield County",
        "population": 63518,
        "lat": 41.0262,
        "lng": -73.6284,
        "metro_area": "Bridgeport-Stamford-Norwalk",
        "region": "Southwest Connecticut"
    },
    "hamden": {
        "name": "Hamden",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "New Haven County",
        "population": 61169,
        "lat": 41.3957,
        "lng": -72.9179,
        "metro_area": "New Haven-Milford",
        "region": "South Central Connecticut"
    },
    "meriden": {
        "name": "Meriden",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "New Haven County",
        "population": 60850,
        "lat": 41.5382,
        "lng": -72.8070,
        "metro_area": "Hartford-West Hartford-East Hartford",
        "region": "Central Connecticut"
    },
    "bristol": {
        "name": "Bristol",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Hartford County",
        "population": 60833,
        "lat": 41.6718,
        "lng": -72.9493,
        "metro_area": "Hartford-West Hartford-East Hartford",
        "region": "Central Connecticut"
    },
    "west-haven": {
        "name": "West Haven",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "New Haven County",
        "population": 55584,
        "lat": 41.2707,
        "lng": -72.9470,
        "metro_area": "New Haven-Milford",
        "region": "South Central Connecticut"
    },
    "milford-ct": {
        "name": "Milford",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "New Haven County",
        "population": 52759,
        "lat": 41.2226,
        "lng": -73.0565,
        "metro_area": "New Haven-Milford",
        "region": "South Central Connecticut"
    },
    "middletown-ct": {
        "name": "Middletown",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Middlesex County",
        "population": 47717,
        "lat": 41.5623,
        "lng": -72.6506,
        "metro_area": "Hartford-West Hartford-East Hartford",
        "region": "Central Connecticut"
    },
    "stratford": {
        "name": "Stratford",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Fairfield County",
        "population": 52508,
        "lat": 41.1845,
        "lng": -73.1332,
        "metro_area": "Bridgeport-Stamford-Norwalk",
        "region": "Southwest Connecticut"
    },
    "east-hartford": {
        "name": "East Hartford",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Hartford County",
        "population": 51252,
        "lat": 41.7620,
        "lng": -72.6122,
        "metro_area": "Hartford-West Hartford-East Hartford",
        "region": "Central Connecticut"
    },
    "torrington": {
        "name": "Torrington",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "Litchfield County",
        "population": 35515,
        "lat": 41.8007,
        "lng": -73.1212,
        "metro_area": "Torrington",
        "region": "Northwest Connecticut"
    },
    "new-london": {
        "name": "New London",
        "state": "Connecticut",
        "state_abbr": "CT",
        "county": "New London County",
        "population": 27367,
        "lat": 41.3556,
        "lng": -72.0995,
        "metro_area": "Norwich-New London",
        "region": "Southeast Connecticut"
    },

    # RHODE ISLAND
    "providence": {
        "name": "Providence",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 190934,
        "lat": 41.8240,
        "lng": -71.4128,
        "metro_area": "Providence-Warwick",
        "region": "New England"
    },
    "warwick": {
        "name": "Warwick",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Kent County",
        "population": 82823,
        "lat": 41.7001,
        "lng": -71.4161,
        "metro_area": "Providence-Warwick",
        "region": "Central Rhode Island"
    },
    "cranston": {
        "name": "Cranston",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 82934,
        "lat": 41.7798,
        "lng": -71.4371,
        "metro_area": "Providence-Warwick",
        "region": "Providence Metro"
    },
    "pawtucket": {
        "name": "Pawtucket",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 75604,
        "lat": 41.8787,
        "lng": -71.3826,
        "metro_area": "Providence-Warwick",
        "region": "Blackstone Valley"
    },
    "east-providence": {
        "name": "East Providence",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 47139,
        "lat": 41.8137,
        "lng": -71.3700,
        "metro_area": "Providence-Warwick",
        "region": "Providence Metro"
    },
    "woonsocket": {
        "name": "Woonsocket",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 43240,
        "lat": 42.0029,
        "lng": -71.5147,
        "metro_area": "Providence-Warwick",
        "region": "Northern Rhode Island"
    },
    "coventry": {
        "name": "Coventry",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Kent County",
        "population": 35688,
        "lat": 41.7001,
        "lng": -71.6828,
        "metro_area": "Providence-Warwick",
        "region": "Western Rhode Island"
    },
    "cumberland": {
        "name": "Cumberland",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 36405,
        "lat": 41.9665,
        "lng": -71.4161,
        "metro_area": "Providence-Warwick",
        "region": "Northern Rhode Island"
    },
    "north-providence": {
        "name": "North Providence",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 34114,
        "lat": 41.8518,
        "lng": -71.4689,
        "metro_area": "Providence-Warwick",
        "region": "Providence Metro"
    },
    "west-warwick": {
        "name": "West Warwick",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Kent County",
        "population": 31012,
        "lat": 41.6959,
        "lng": -71.5201,
        "metro_area": "Providence-Warwick",
        "region": "Central Rhode Island"
    },
    "johnston": {
        "name": "Johnston",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 29568,
        "lat": 41.8298,
        "lng": -71.5020,
        "metro_area": "Providence-Warwick",
        "region": "Providence Metro"
    },
    "newport": {
        "name": "Newport",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Newport County",
        "population": 25441,
        "lat": 41.4901,
        "lng": -71.3128,
        "metro_area": "Providence-Warwick",
        "region": "Newport County"
    },
    "south-kingstown": {
        "name": "South Kingstown",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Washington County",
        "population": 31931,
        "lat": 41.4618,
        "lng": -71.5201,
        "metro_area": "Providence-Warwick",
        "region": "South County"
    },
    "westerly": {
        "name": "Westerly",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Washington County",
        "population": 23359,
        "lat": 41.3776,
        "lng": -71.7827,
        "metro_area": "Providence-Warwick",
        "region": "South County"
    },
    "lincoln-ri": {
        "name": "Lincoln",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 22529,
        "lat": 41.9154,
        "lng": -71.4370,
        "metro_area": "Providence-Warwick",
        "region": "Northern Rhode Island"
    },
    "central-falls": {
        "name": "Central Falls",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 22583,
        "lat": 41.8901,
        "lng": -71.3928,
        "metro_area": "Providence-Warwick",
        "region": "Blackstone Valley"
    },
    "bristol-ri": {
        "name": "Bristol",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Bristol County",
        "population": 22493,
        "lat": 41.6771,
        "lng": -71.2662,
        "metro_area": "Providence-Warwick",
        "region": "East Bay"
    },
    "smithfield": {
        "name": "Smithfield",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Providence County",
        "population": 21430,
        "lat": 41.9209,
        "lng": -71.5495,
        "metro_area": "Providence-Warwick",
        "region": "Northern Rhode Island"
    },
    "middletown-ri": {
        "name": "Middletown",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Newport County",
        "population": 17075,
        "lat": 41.5151,
        "lng": -71.2906,
        "metro_area": "Providence-Warwick",
        "region": "Newport County"
    },
    "portsmouth-ri": {
        "name": "Portsmouth",
        "state": "Rhode Island",
        "state_abbr": "RI",
        "county": "Newport County",
        "population": 17871,
        "lat": 41.6026,
        "lng": -71.2662,
        "metro_area": "Providence-Warwick",
        "region": "East Bay"
    },

    # NEW JERSEY
    "newark": {
        "name": "Newark",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Essex County",
        "population": 311549,
        "lat": 40.7357,
        "lng": -74.1724,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Northeast New Jersey"
    },
    "jersey-city": {
        "name": "Jersey City",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Hudson County",
        "population": 292449,
        "lat": 40.7282,
        "lng": -74.0776,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Northeast New Jersey"
    },
    "paterson": {
        "name": "Paterson",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Passaic County",
        "population": 159732,
        "lat": 40.9168,
        "lng": -74.1718,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Northeast New Jersey"
    },
    "elizabeth": {
        "name": "Elizabeth",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Union County",
        "population": 137298,
        "lat": 40.6640,
        "lng": -74.2107,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Central New Jersey"
    },
    "lakewood": {
        "name": "Lakewood",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Ocean County",
        "population": 135158,
        "lat": 40.0978,
        "lng": -74.2176,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Central New Jersey"
    },
    "edison": {
        "name": "Edison",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Middlesex County",
        "population": 107588,
        "lat": 40.5187,
        "lng": -74.4121,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Central New Jersey"
    },
    "woodbridge": {
        "name": "Woodbridge",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Middlesex County",
        "population": 103639,
        "lat": 40.5576,
        "lng": -74.2845,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Central New Jersey"
    },
    "toms-river": {
        "name": "Toms River",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Ocean County",
        "population": 95438,
        "lat": 39.9537,
        "lng": -74.1979,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Central New Jersey"
    },
    "hamilton-township": {
        "name": "Hamilton Township",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Mercer County",
        "population": 92297,
        "lat": 40.2290,
        "lng": -74.6537,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Central New Jersey"
    },
    "trenton": {
        "name": "Trenton",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Mercer County",
        "population": 90871,
        "lat": 40.2171,
        "lng": -74.7429,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Central New Jersey"
    },
    "clifton": {
        "name": "Clifton",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Passaic County",
        "population": 90296,
        "lat": 40.8584,
        "lng": -74.1638,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Northeast New Jersey"
    },
    "camden": {
        "name": "Camden",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Camden County",
        "population": 71791,
        "lat": 39.9259,
        "lng": -75.1196,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "South Jersey"
    },
    "passaic": {
        "name": "Passaic",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Passaic County",
        "population": 70537,
        "lat": 40.8568,
        "lng": -74.1284,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Northeast New Jersey"
    },
    "union-city": {
        "name": "Union City",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Hudson County",
        "population": 68589,
        "lat": 40.7662,
        "lng": -74.0376,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Northeast New Jersey"
    },
    "bayonne": {
        "name": "Bayonne",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Hudson County",
        "population": 71686,
        "lat": 40.6687,
        "lng": -74.1143,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Northeast New Jersey"
    },
    "east-orange": {
        "name": "East Orange",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Essex County",
        "population": 69612,
        "lat": 40.7673,
        "lng": -74.2049,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Northeast New Jersey"
    },
    "vineland": {
        "name": "Vineland",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Cumberland County",
        "population": 60724,
        "lat": 39.4864,
        "lng": -75.0260,
        "metro_area": "Vineland-Millville-Bridgeton",
        "region": "South Jersey"
    },
    "new-brunswick": {
        "name": "New Brunswick",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Middlesex County",
        "population": 55956,
        "lat": 40.4862,
        "lng": -74.4518,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Central New Jersey"
    },
    "irvington": {
        "name": "Irvington",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Essex County",
        "population": 61176,
        "lat": 40.7315,
        "lng": -74.2346,
        "metro_area": "New York-Newark-Jersey City",
        "region": "Northeast New Jersey"
    },
    "atlantic-city": {
        "name": "Atlantic City",
        "state": "New Jersey",
        "state_abbr": "NJ",
        "county": "Atlantic County",
        "population": 38497,
        "lat": 39.3643,
        "lng": -74.4229,
        "metro_area": "Atlantic City-Hammonton",
        "region": "South Jersey"
    },

    # VERMONT
    "burlington-vt": {
        "name": "Burlington",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Chittenden County",
        "population": 44743,
        "lat": 44.4759,
        "lng": -73.2121,
        "metro_area": "Burlington-South Burlington",
        "region": "Champlain Valley"
    },
    "south-burlington": {
        "name": "South Burlington",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Chittenden County",
        "population": 20292,
        "lat": 44.4669,
        "lng": -73.1709,
        "metro_area": "Burlington-South Burlington",
        "region": "Champlain Valley"
    },
    "colchester": {
        "name": "Colchester",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Chittenden County",
        "population": 17524,
        "lat": 44.5439,
        "lng": -73.1315,
        "metro_area": "Burlington-South Burlington",
        "region": "Champlain Valley"
    },
    "rutland-city": {
        "name": "Rutland",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Rutland County",
        "population": 15807,
        "lat": 43.6106,
        "lng": -72.9726,
        "metro_area": "Rutland",
        "region": "Central Vermont"
    },
    "essex": {
        "name": "Essex",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Chittenden County",
        "population": 22094,
        "lat": 44.4906,
        "lng": -73.1120,
        "metro_area": "Burlington-South Burlington",
        "region": "Champlain Valley"
    },
    "bennington": {
        "name": "Bennington",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Bennington County",
        "population": 15333,
        "lat": 42.8781,
        "lng": -73.1965,
        "metro_area": "Bennington",
        "region": "Southwest Vermont"
    },
    "brattleboro": {
        "name": "Brattleboro",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Windham County",
        "population": 12046,
        "lat": 42.8509,
        "lng": -72.5579,
        "metro_area": "Brattleboro",
        "region": "Southeast Vermont"
    },
    "milton": {
        "name": "Milton",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Chittenden County",
        "population": 10723,
        "lat": 44.6361,
        "lng": -73.1120,
        "metro_area": "Burlington-South Burlington",
        "region": "Champlain Valley"
    },
    "williston": {
        "name": "Williston",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Chittenden County",
        "population": 10103,
        "lat": 44.4298,
        "lng": -73.0931,
        "metro_area": "Burlington-South Burlington",
        "region": "Champlain Valley"
    },
    "montpelier": {
        "name": "Montpelier",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Washington County",
        "population": 8074,
        "lat": 44.2601,
        "lng": -72.5806,
        "metro_area": "Montpelier",
        "region": "Central Vermont"
    },
    "winooski": {
        "name": "Winooski",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Chittenden County",
        "population": 7997,
        "lat": 44.4906,
        "lng": -73.1837,
        "metro_area": "Burlington-South Burlington",
        "region": "Champlain Valley"
    },
    "st-albans": {
        "name": "St. Albans",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Franklin County",
        "population": 6877,
        "lat": 44.8111,
        "lng": -73.0848,
        "metro_area": "St. Albans",
        "region": "Northwest Vermont"
    },
    "newport-vt": {
        "name": "Newport",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Orleans County",
        "population": 4455,
        "lat": 44.9364,
        "lng": -72.2012,
        "metro_area": "Newport",
        "region": "Northeast Kingdom"
    },
    "vergennes": {
        "name": "Vergennes",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Addison County",
        "population": 2553,
        "lat": 44.1687,
        "lng": -73.2540,
        "metro_area": "Vergennes",
        "region": "Champlain Valley"
    },
    "st-johnsbury": {
        "name": "St. Johnsbury",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Caledonia County",
        "population": 7364,
        "lat": 44.4192,
        "lng": -72.0151,
        "metro_area": "St. Johnsbury",
        "region": "Northeast Kingdom"
    },
    "middlebury": {
        "name": "Middlebury",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Addison County",
        "population": 9152,
        "lat": 44.0175,
        "lng": -73.1673,
        "metro_area": "Middlebury",
        "region": "Central Vermont"
    },
    "barre-city": {
        "name": "Barre",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Washington County",
        "population": 8491,
        "lat": 44.1970,
        "lng": -72.5020,
        "metro_area": "Barre",
        "region": "Central Vermont"
    },
    "white-river-junction": {
        "name": "White River Junction",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Windsor County",
        "population": 2528,
        "lat": 43.6489,
        "lng": -72.3198,
        "metro_area": "White River Junction",
        "region": "Upper Valley"
    },
    "springfield-vt": {
        "name": "Springfield",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Windsor County",
        "population": 9062,
        "lat": 43.3000,
        "lng": -72.4851,
        "metro_area": "Springfield",
        "region": "Southern Vermont"
    },
    "shelburne": {
        "name": "Shelburne",
        "state": "Vermont",
        "state_abbr": "VT",
        "county": "Chittenden County",
        "population": 7717,
        "lat": 44.3795,
        "lng": -73.2262,
        "metro_area": "Burlington-South Burlington",
        "region": "Champlain Valley"
    },

    # NEW HAMPSHIRE
    "manchester-nh": {
        "name": "Manchester",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Hillsborough County",
        "population": 115644,
        "lat": 42.9956,
        "lng": -71.4548,
        "metro_area": "Manchester-Nashua",
        "region": "Southern New Hampshire"
    },
    "nashua": {
        "name": "Nashua",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Hillsborough County",
        "population": 91322,
        "lat": 42.7654,
        "lng": -71.4676,
        "metro_area": "Manchester-Nashua",
        "region": "Southern New Hampshire"
    },
    "concord-nh": {
        "name": "Concord",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Merrimack County",
        "population": 43976,
        "lat": 43.2081,
        "lng": -71.5376,
        "metro_area": "Concord",
        "region": "Central New Hampshire"
    },
    "derry": {
        "name": "Derry",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Rockingham County",
        "population": 34317,
        "lat": 42.8870,
        "lng": -71.3273,
        "metro_area": "Manchester-Nashua",
        "region": "Southern New Hampshire"
    },
    "rochester-nh": {
        "name": "Rochester",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Strafford County",
        "population": 32492,
        "lat": 43.3042,
        "lng": -70.9756,
        "metro_area": "Rochester",
        "region": "Seacoast"
    },
    "dover": {
        "name": "Dover",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Strafford County",
        "population": 32741,
        "lat": 43.1979,
        "lng": -70.8737,
        "metro_area": "Dover-Durham",
        "region": "Seacoast"
    },
    "salem-nh": {
        "name": "Salem",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Rockingham County",
        "population": 30089,
        "lat": 42.7881,
        "lng": -71.2009,
        "metro_area": "Manchester-Nashua",
        "region": "Southern New Hampshire"
    },
    "merrimack": {
        "name": "Merrimack",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Hillsborough County",
        "population": 26632,
        "lat": 42.8653,
        "lng": -71.4912,
        "metro_area": "Manchester-Nashua",
        "region": "Southern New Hampshire"
    },
    "hudson": {
        "name": "Hudson",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Hillsborough County",
        "population": 25394,
        "lat": 42.7626,
        "lng": -71.4340,
        "metro_area": "Manchester-Nashua",
        "region": "Southern New Hampshire"
    },
    "londonderry": {
        "name": "Londonderry",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Rockingham County",
        "population": 25826,
        "lat": 42.8653,
        "lng": -71.3740,
        "metro_area": "Manchester-Nashua",
        "region": "Southern New Hampshire"
    },
    "keene": {
        "name": "Keene",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Cheshire County",
        "population": 23047,
        "lat": 42.9342,
        "lng": -72.2781,
        "metro_area": "Keene",
        "region": "Southwest New Hampshire"
    },
    "portsmouth": {
        "name": "Portsmouth",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Rockingham County",
        "population": 22477,
        "lat": 43.0718,
        "lng": -70.7626,
        "metro_area": "Portsmouth",
        "region": "Seacoast"
    },
    "laconia": {
        "name": "Laconia",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Belknap County",
        "population": 16871,
        "lat": 43.5281,
        "lng": -71.4703,
        "metro_area": "Laconia",
        "region": "Lakes Region"
    },
    "claremont": {
        "name": "Claremont",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Sullivan County",
        "population": 12969,
        "lat": 43.3767,
        "lng": -72.3464,
        "metro_area": "Claremont",
        "region": "Upper Valley"
    },
    "lebanon": {
        "name": "Lebanon",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Grafton County",
        "population": 14282,
        "lat": 43.6422,
        "lng": -72.2517,
        "metro_area": "Lebanon",
        "region": "Upper Valley"
    },
    "exeter": {
        "name": "Exeter",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Rockingham County",
        "population": 16049,
        "lat": 42.9814,
        "lng": -70.9478,
        "metro_area": "Exeter",
        "region": "Seacoast"
    },
    "franklin": {
        "name": "Franklin",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Merrimack County",
        "population": 8741,
        "lat": 43.4417,
        "lng": -71.6470,
        "metro_area": "Franklin",
        "region": "Central New Hampshire"
    },
    "somersworth": {
        "name": "Somersworth",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Strafford County",
        "population": 11021,
        "lat": 43.2537,
        "lng": -70.8787,
        "metro_area": "Dover-Durham",
        "region": "Seacoast"
    },
    "berlin": {
        "name": "Berlin",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Coos County",
        "population": 9425,
        "lat": 44.4689,
        "lng": -71.1850,
        "metro_area": "Berlin",
        "region": "North Country"
    },
    "hampton": {
        "name": "Hampton",
        "state": "New Hampshire",
        "state_abbr": "NH",
        "county": "Rockingham County",
        "population": 16214,
        "lat": 42.9376,
        "lng": -70.8189,
        "metro_area": "Portsmouth",
        "region": "Seacoast"
    },

    # MAINE
    "portland-me": {
        "name": "Portland",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Cumberland County",
        "population": 68408,
        "lat": 43.6591,
        "lng": -70.2568,
        "metro_area": "Portland-South Portland",
        "region": "Southern Maine"
    },
    "lewiston": {
        "name": "Lewiston",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Androscoggin County",
        "population": 37121,
        "lat": 44.1004,
        "lng": -70.2148,
        "metro_area": "Lewiston-Auburn",
        "region": "Central Maine"
    },
    "bangor": {
        "name": "Bangor",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Penobscot County",
        "population": 31753,
        "lat": 44.8016,
        "lng": -68.7712,
        "metro_area": "Bangor",
        "region": "Central Maine"
    },
    "south-portland": {
        "name": "South Portland",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Cumberland County",
        "population": 26498,
        "lat": 43.6415,
        "lng": -70.2409,
        "metro_area": "Portland-South Portland",
        "region": "Southern Maine"
    },
    "auburn": {
        "name": "Auburn",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Androscoggin County",
        "population": 24061,
        "lat": 44.0979,
        "lng": -70.2311,
        "metro_area": "Lewiston-Auburn",
        "region": "Central Maine"
    },
    "biddeford": {
        "name": "Biddeford",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "York County",
        "population": 22552,
        "lat": 43.4926,
        "lng": -70.4533,
        "metro_area": "Portland-South Portland",
        "region": "Southern Maine"
    },
    "augusta": {
        "name": "Augusta",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Kennebec County",
        "population": 18899,
        "lat": 44.3106,
        "lng": -69.7795,
        "metro_area": "Augusta",
        "region": "Central Maine"
    },
    "sanford": {
        "name": "Sanford",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "York County",
        "population": 21982,
        "lat": 43.4395,
        "lng": -70.7739,
        "metro_area": "Sanford",
        "region": "Southern Maine"
    },
    "saco": {
        "name": "Saco",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "York County",
        "population": 20381,
        "lat": 43.5009,
        "lng": -70.4428,
        "metro_area": "Portland-South Portland",
        "region": "Southern Maine"
    },
    "westbrook": {
        "name": "Westbrook",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Cumberland County",
        "population": 20400,
        "lat": 43.6770,
        "lng": -70.3712,
        "metro_area": "Portland-South Portland",
        "region": "Southern Maine"
    },
    "waterville": {
        "name": "Waterville",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Kennebec County",
        "population": 15828,
        "lat": 44.5487,
        "lng": -69.6317,
        "metro_area": "Waterville",
        "region": "Central Maine"
    },
    "presque-isle": {
        "name": "Presque Isle",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Aroostook County",
        "population": 8797,
        "lat": 46.6819,
        "lng": -68.0161,
        "metro_area": "Presque Isle",
        "region": "Northern Maine"
    },
    "brunswick": {
        "name": "Brunswick",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Cumberland County",
        "population": 21756,
        "lat": 43.9140,
        "lng": -69.9653,
        "metro_area": "Brunswick",
        "region": "Midcoast"
    },
    "gardiner": {
        "name": "Gardiner",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Kennebec County",
        "population": 5572,
        "lat": 44.2298,
        "lng": -69.7756,
        "metro_area": "Gardiner",
        "region": "Central Maine"
    },
    "old-orchard-beach": {
        "name": "Old Orchard Beach",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "York County",
        "population": 8960,
        "lat": 43.5148,
        "lng": -70.3781,
        "metro_area": "Portland-South Portland",
        "region": "Southern Maine"
    },
    "caribou": {
        "name": "Caribou",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Aroostook County",
        "population": 7396,
        "lat": 46.8628,
        "lng": -68.0127,
        "metro_area": "Caribou",
        "region": "Northern Maine"
    },
    "rockland": {
        "name": "Rockland",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Knox County",
        "population": 6936,
        "lat": 44.1037,
        "lng": -69.1097,
        "metro_area": "Rockland",
        "region": "Midcoast"
    },
    "ellsworth": {
        "name": "Ellsworth",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Hancock County",
        "population": 8399,
        "lat": 44.5434,
        "lng": -68.4198,
        "metro_area": "Ellsworth",
        "region": "Down East"
    },
    "belfast": {
        "name": "Belfast",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Waldo County",
        "population": 6938,
        "lat": 44.4259,
        "lng": -69.0067,
        "metro_area": "Belfast",
        "region": "Midcoast"
    },
    "calais": {
        "name": "Calais",
        "state": "Maine",
        "state_abbr": "ME",
        "county": "Washington County",
        "population": 3079,
        "lat": 45.1737,
        "lng": -67.2425,
        "metro_area": "Calais",
        "region": "Down East"
    },

    # MARYLAND
    "baltimore": {
        "name": "Baltimore",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Independent City",
        "population": 585708,
        "lat": 39.2904,
        "lng": -76.6122,
        "metro_area": "Baltimore-Columbia-Towson",
        "region": "Central Maryland"
    },
    "frederick": {
        "name": "Frederick",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Frederick County",
        "population": 78050,
        "lat": 39.4143,
        "lng": -77.4105,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Western Maryland"
    },
    "rockville": {
        "name": "Rockville",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Montgomery County",
        "population": 67117,
        "lat": 39.0840,
        "lng": -77.1528,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Washington Suburbs"
    },
    "gaithersburg": {
        "name": "Gaithersburg",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Montgomery County",
        "population": 69657,
        "lat": 39.1434,
        "lng": -77.2014,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Washington Suburbs"
    },
    "bowie": {
        "name": "Bowie",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Prince George's County",
        "population": 58329,
        "lat": 38.9426,
        "lng": -76.7302,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Washington Suburbs"
    },
    "hagerstown": {
        "name": "Hagerstown",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Washington County",
        "population": 43527,
        "lat": 39.6417,
        "lng": -77.7200,
        "metro_area": "Hagerstown-Martinsburg",
        "region": "Western Maryland"
    },
    "annapolis": {
        "name": "Annapolis",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Anne Arundel County",
        "population": 40812,
        "lat": 38.9784,
        "lng": -76.4951,
        "metro_area": "Baltimore-Columbia-Towson",
        "region": "Central Maryland"
    },
    "college-park": {
        "name": "College Park",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Prince George's County",
        "population": 32303,
        "lat": 38.9807,
        "lng": -76.9369,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Washington Suburbs"
    },
    "salisbury": {
        "name": "Salisbury",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Wicomico County",
        "population": 33050,
        "lat": 38.3607,
        "lng": -75.5994,
        "metro_area": "Salisbury",
        "region": "Eastern Shore"
    },
    "laurel": {
        "name": "Laurel",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Prince George's County",
        "population": 29666,
        "lat": 39.0993,
        "lng": -76.8483,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Washington Suburbs"
    },
    "greenbelt": {
        "name": "Greenbelt",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Prince George's County",
        "population": 23253,
        "lat": 38.9912,
        "lng": -76.8758,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Washington Suburbs"
    },
    "takoma-park": {
        "name": "Takoma Park",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Montgomery County",
        "population": 17629,
        "lat": 38.9807,
        "lng": -77.0077,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Washington Suburbs"
    },
    "westminster": {
        "name": "Westminster",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Carroll County",
        "population": 18590,
        "lat": 39.5751,
        "lng": -76.9958,
        "metro_area": "Baltimore-Columbia-Towson",
        "region": "Central Maryland"
    },
    "cumberland": {
        "name": "Cumberland",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Allegany County",
        "population": 19075,
        "lat": 39.6526,
        "lng": -78.7625,
        "metro_area": "Cumberland",
        "region": "Western Maryland"
    },
    "hyattsville": {
        "name": "Hyattsville",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Prince George's County",
        "population": 21187,
        "lat": 38.9559,
        "lng": -76.9456,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Washington Suburbs"
    },
    "cambridge-md": {
        "name": "Cambridge",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Dorchester County",
        "population": 13096,
        "lat": 38.5632,
        "lng": -76.0783,
        "metro_area": "Cambridge",
        "region": "Eastern Shore"
    },
    "easton": {
        "name": "Easton",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Talbot County",
        "population": 16589,
        "lat": 38.7740,
        "lng": -76.0777,
        "metro_area": "Easton",
        "region": "Eastern Shore"
    },
    "ocean-city": {
        "name": "Ocean City",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Worcester County",
        "population": 6844,
        "lat": 38.3365,
        "lng": -75.0849,
        "metro_area": "Ocean City",
        "region": "Eastern Shore"
    },
    "havre-de-grace": {
        "name": "Havre de Grace",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Harford County",
        "population": 14856,
        "lat": 39.5490,
        "lng": -76.0916,
        "metro_area": "Baltimore-Columbia-Towson",
        "region": "Central Maryland"
    },
    "elkton": {
        "name": "Elkton",
        "state": "Maryland",
        "state_abbr": "MD",
        "county": "Cecil County",
        "population": 15668,
        "lat": 39.6062,
        "lng": -75.8332,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Northeast Maryland"
    },

    # DELAWARE
    "wilmington": {
        "name": "Wilmington",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "New Castle County",
        "population": 70898,
        "lat": 39.7391,
        "lng": -75.5398,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Northern Delaware"
    },
    "dover-de": {
        "name": "Dover",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Kent County",
        "population": 39403,
        "lat": 39.1612,
        "lng": -75.5277,
        "metro_area": "Dover",
        "region": "Central Delaware"
    },
    "newark-de": {
        "name": "Newark",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "New Castle County",
        "population": 31454,
        "lat": 39.6837,
        "lng": -75.7497,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Northern Delaware"
    },
    "middletown-de": {
        "name": "Middletown",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "New Castle County",
        "population": 23192,
        "lat": 39.4495,
        "lng": -75.7163,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Northern Delaware"
    },
    "smyrna": {
        "name": "Smyrna",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Kent County",
        "population": 12883,
        "lat": 39.2998,
        "lng": -75.6047,
        "metro_area": "Dover",
        "region": "Central Delaware"
    },
    "milford-de": {
        "name": "Milford",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Kent County",
        "population": 11190,
        "lat": 38.9126,
        "lng": -75.4277,
        "metro_area": "Milford",
        "region": "Southern Delaware"
    },
    "seaford": {
        "name": "Seaford",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Sussex County",
        "population": 8335,
        "lat": 38.6412,
        "lng": -75.6111,
        "metro_area": "Seaford",
        "region": "Southern Delaware"
    },
    "georgetown-de": {
        "name": "Georgetown",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Sussex County",
        "population": 7893,
        "lat": 38.6901,
        "lng": -75.3854,
        "metro_area": "Georgetown",
        "region": "Southern Delaware"
    },
    "harrington": {
        "name": "Harrington",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Kent County",
        "population": 3885,
        "lat": 38.9223,
        "lng": -75.5797,
        "metro_area": "Harrington",
        "region": "Central Delaware"
    },
    "laurel-de": {
        "name": "Laurel",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Sussex County",
        "population": 4363,
        "lat": 38.5565,
        "lng": -75.5713,
        "metro_area": "Laurel",
        "region": "Southern Delaware"
    },
    "rehoboth-beach": {
        "name": "Rehoboth Beach",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Sussex County",
        "population": 1108,
        "lat": 38.7196,
        "lng": -75.0757,
        "metro_area": "Rehoboth Beach",
        "region": "Coastal Delaware"
    },
    "bethany-beach": {
        "name": "Bethany Beach",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Sussex County",
        "population": 1108,
        "lat": 38.5390,
        "lng": -75.0638,
        "metro_area": "Bethany Beach",
        "region": "Coastal Delaware"
    },
    "lewes": {
        "name": "Lewes",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Sussex County",
        "population": 3303,
        "lat": 38.7744,
        "lng": -75.1391,
        "metro_area": "Lewes",
        "region": "Coastal Delaware"
    },
    "new-castle": {
        "name": "New Castle",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "New Castle County",
        "population": 5285,
        "lat": 39.6621,
        "lng": -75.5660,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Northern Delaware"
    },
    "delmar-de": {
        "name": "Delmar",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Sussex County",
        "population": 1597,
        "lat": 38.4565,
        "lng": -75.5771,
        "metro_area": "Salisbury",
        "region": "Southern Delaware"
    },
    "clayton": {
        "name": "Clayton",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Kent County",
        "population": 3254,
        "lat": 39.2901,
        "lng": -75.6305,
        "metro_area": "Dover",
        "region": "Central Delaware"
    },
    "dagsboro": {
        "name": "Dagsboro",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "Sussex County",
        "population": 805,
        "lat": 38.5465,
        "lng": -75.2468,
        "metro_area": "Dagsboro",
        "region": "Southern Delaware"
    },
    "elsmere": {
        "name": "Elsmere",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "New Castle County",
        "population": 6131,
        "lat": 39.7387,
        "lng": -75.5935,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Northern Delaware"
    },
    "newport-de": {
        "name": "Newport",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "New Castle County",
        "population": 1055,
        "lat": 39.7137,
        "lng": -75.6063,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Northern Delaware"
    },
    "odessa": {
        "name": "Odessa",
        "state": "Delaware",
        "state_abbr": "DE",
        "county": "New Castle County",
        "population": 364,
        "lat": 39.4587,
        "lng": -75.6624,
        "metro_area": "Philadelphia-Camden-Wilmington",
        "region": "Northern Delaware"
    },

    # WEST VIRGINIA
    "charleston-wv": {
        "name": "Charleston",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Kanawha County",
        "population": 46536,
        "lat": 38.3498,
        "lng": -81.6326,
        "metro_area": "Charleston",
        "region": "Central West Virginia"
    },
    "huntington": {
        "name": "Huntington",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Cabell County",
        "population": 45325,
        "lat": 38.4192,
        "lng": -82.4452,
        "metro_area": "Huntington-Ashland",
        "region": "Western West Virginia"
    },
    "morgantown": {
        "name": "Morgantown",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Monongalia County",
        "population": 30347,
        "lat": 39.6295,
        "lng": -79.9553,
        "metro_area": "Morgantown",
        "region": "Northern West Virginia"
    },
    "parkersburg": {
        "name": "Parkersburg",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Wood County",
        "population": 29738,
        "lat": 39.2667,
        "lng": -81.5615,
        "metro_area": "Parkersburg-Vienna",
        "region": "Northwestern West Virginia"
    },
    "wheeling": {
        "name": "Wheeling",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Ohio County",
        "population": 26771,
        "lat": 40.0640,
        "lng": -80.7209,
        "metro_area": "Wheeling",
        "region": "Northern West Virginia"
    },
    "martinsburg": {
        "name": "Martinsburg",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Berkeley County",
        "population": 18773,
        "lat": 39.4565,
        "lng": -77.9636,
        "metro_area": "Hagerstown-Martinsburg",
        "region": "Eastern Panhandle"
    },
    "fairmont": {
        "name": "Fairmont",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Marion County",
        "population": 18313,
        "lat": 39.4851,
        "lng": -80.1426,
        "metro_area": "Fairmont",
        "region": "North Central West Virginia"
    },
    "beckley": {
        "name": "Beckley",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Raleigh County",
        "population": 15049,
        "lat": 37.7782,
        "lng": -81.1882,
        "metro_area": "Beckley",
        "region": "Southern West Virginia"
    },
    "clarksburg": {
        "name": "Clarksburg",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Harrison County",
        "population": 15743,
        "lat": 39.2806,
        "lng": -80.3445,
        "metro_area": "Clarksburg",
        "region": "North Central West Virginia"
    },
    "hurricane": {
        "name": "Hurricane",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Putnam County",
        "population": 6934,
        "lat": 38.4320,
        "lng": -82.0190,
        "metro_area": "Charleston",
        "region": "Central West Virginia"
    },
    "south-charleston": {
        "name": "South Charleston",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Kanawha County",
        "population": 12461,
        "lat": 38.3687,
        "lng": -81.7007,
        "metro_area": "Charleston",
        "region": "Central West Virginia"
    },
    "shepherdstown": {
        "name": "Shepherdstown",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Jefferson County",
        "population": 1734,
        "lat": 39.4307,
        "lng": -77.8042,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Eastern Panhandle"
    },
    "charles-town": {
        "name": "Charles Town",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Jefferson County",
        "population": 6534,
        "lat": 39.2890,
        "lng": -77.8600,
        "metro_area": "Washington-Arlington-Alexandria",
        "region": "Eastern Panhandle"
    },
    "bridgeport": {
        "name": "Bridgeport",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Harrison County",
        "population": 9222,
        "lat": 39.2834,
        "lng": -80.2534,
        "metro_area": "Clarksburg",
        "region": "North Central West Virginia"
    },
    "buckhannon": {
        "name": "Buckhannon",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Upshur County",
        "population": 5299,
        "lat": 38.9959,
        "lng": -80.2320,
        "metro_area": "Buckhannon",
        "region": "Central West Virginia"
    },
    "lewisburg": {
        "name": "Lewisburg",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Greenbrier County",
        "population": 3930,
        "lat": 37.8018,
        "lng": -80.4457,
        "metro_area": "Lewisburg",
        "region": "Southeastern West Virginia"
    },
    "keyser": {
        "name": "Keyser",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Mineral County",
        "population": 4624,
        "lat": 39.4362,
        "lng": -78.9811,
        "metro_area": "Cumberland",
        "region": "Eastern Panhandle"
    },
    "elkins": {
        "name": "Elkins",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Randolph County",
        "population": 6964,
        "lat": 38.9262,
        "lng": -79.8473,
        "metro_area": "Elkins",
        "region": "Central West Virginia"
    },
    "summersville": {
        "name": "Summersville",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Nicholas County",
        "population": 3572,
        "lat": 38.2787,
        "lng": -80.8551,
        "metro_area": "Summersville",
        "region": "Central West Virginia"
    },
    "point-pleasant": {
        "name": "Point Pleasant",
        "state": "West Virginia",
        "state_abbr": "WV",
        "county": "Mason County",
        "population": 4101,
        "lat": 38.8484,
        "lng": -82.1368,
        "metro_area": "Point Pleasant",
        "region": "Western West Virginia"
    }
}