# Top 20 Cities Data for Western US States (2024)
# Compiled for Django Application - Skerritt Economics

WESTERN_STATES_CITIES = {
    # CALIFORNIA - Top 20 Cities
    "los-angeles": {
        "name": "Los Angeles",
        "state": "California",
        "state_abbr": "CA",
        "county": "Los Angeles County",
        "population": 3820914,
        "lat": 34.0522,
        "lng": -118.2437,
        "metro_area": "Los Angeles-Long Beach-Anaheim Metropolitan Area",
        "region": "Southern California"
    },
    "san-diego": {
        "name": "San Diego",
        "state": "California", 
        "state_abbr": "CA",
        "county": "San Diego County",
        "population": 1388320,
        "lat": 32.7157,
        "lng": -117.1611,
        "metro_area": "San Diego-Chula Vista-Carlsbad Metropolitan Area",
        "region": "Southern California"
    },
    "san-jose": {
        "name": "San Jose",
        "state": "California",
        "state_abbr": "CA", 
        "county": "Santa Clara County",
        "population": 969655,
        "lat": 37.3382,
        "lng": -121.8863,
        "metro_area": "San Jose-Sunnyvale-Santa Clara Metropolitan Area",
        "region": "Northern California"
    },
    "san-francisco": {
        "name": "San Francisco",
        "state": "California",
        "state_abbr": "CA",
        "county": "San Francisco County",
        "population": 808988,
        "lat": 37.7749,
        "lng": -122.4194,
        "metro_area": "San Francisco-Oakland-Berkeley Metropolitan Area",
        "region": "Northern California"
    },
    "fresno": {
        "name": "Fresno", 
        "state": "California",
        "state_abbr": "CA",
        "county": "Fresno County",
        "population": 545716,
        "lat": 36.7468,
        "lng": -119.7726,
        "metro_area": "Fresno Metropolitan Area",
        "region": "Central Valley"
    },
    "sacramento": {
        "name": "Sacramento",
        "state": "California",
        "state_abbr": "CA",
        "county": "Sacramento County", 
        "population": 525400,
        "lat": 38.5556,
        "lng": -121.4689,
        "metro_area": "Sacramento-Roseville-Arden-Arcade Metropolitan Area",
        "region": "Northern California"
    },
    "long-beach": {
        "name": "Long Beach",
        "state": "California",
        "state_abbr": "CA",
        "county": "Los Angeles County",
        "population": 456062,
        "lat": 33.7701,
        "lng": -118.1937,
        "metro_area": "Los Angeles-Long Beach-Anaheim Metropolitan Area", 
        "region": "Southern California"
    },
    "oakland": {
        "name": "Oakland",
        "state": "California",
        "state_abbr": "CA",
        "county": "Alameda County",
        "population": 434000,
        "lat": 37.8044,
        "lng": -122.2711,
        "metro_area": "San Francisco-Oakland-Berkeley Metropolitan Area",
        "region": "Northern California"
    },
    "bakersfield": {
        "name": "Bakersfield",
        "state": "California",
        "state_abbr": "CA", 
        "county": "Kern County",
        "population": 419000,
        "lat": 35.3733,
        "lng": -119.0187,
        "metro_area": "Bakersfield Metropolitan Area",
        "region": "Central Valley"
    },
    "anaheim": {
        "name": "Anaheim",
        "state": "California",
        "state_abbr": "CA",
        "county": "Orange County",
        "population": 346824,
        "lat": 33.8366,
        "lng": -117.9143,
        "metro_area": "Los Angeles-Long Beach-Anaheim Metropolitan Area",
        "region": "Southern California"
    },
    "santa-ana": {
        "name": "Santa Ana",
        "state": "California",
        "state_abbr": "CA",
        "county": "Orange County",
        "population": 310227,
        "lat": 33.7455,
        "lng": -117.8677,
        "metro_area": "Los Angeles-Long Beach-Anaheim Metropolitan Area",
        "region": "Southern California"
    },
    "riverside": {
        "name": "Riverside", 
        "state": "California",
        "state_abbr": "CA",
        "county": "Riverside County",
        "population": 314998,
        "lat": 33.9533,
        "lng": -117.3962,
        "metro_area": "Riverside-San Bernardino-Ontario Metropolitan Area",
        "region": "Inland Empire"
    },
    "stockton": {
        "name": "Stockton",
        "state": "California",
        "state_abbr": "CA",
        "county": "San Joaquin County",
        "population": 310496,
        "lat": 37.9577,
        "lng": -121.2908,
        "metro_area": "Stockton-Lodi Metropolitan Area",
        "region": "Central Valley"
    },
    "irvine": {
        "name": "Irvine",
        "state": "California",
        "state_abbr": "CA",
        "county": "Orange County",
        "population": 307670,
        "lat": 33.6846,
        "lng": -117.8265,
        "metro_area": "Los Angeles-Long Beach-Anaheim Metropolitan Area",
        "region": "Southern California"
    },
    "chula-vista": {
        "name": "Chula Vista",
        "state": "California", 
        "state_abbr": "CA",
        "county": "San Diego County",
        "population": 275487,
        "lat": 32.6401,
        "lng": -117.0842,
        "metro_area": "San Diego-Chula Vista-Carlsbad Metropolitan Area",
        "region": "Southern California"
    },
    "fremont": {
        "name": "Fremont",
        "state": "California",
        "state_abbr": "CA",
        "county": "Alameda County", 
        "population": 230504,
        "lat": 37.5485,
        "lng": -121.9886,
        "metro_area": "San Francisco-Oakland-Berkeley Metropolitan Area",
        "region": "Northern California"
    },
    "san-bernardino": {
        "name": "San Bernardino",
        "state": "California",
        "state_abbr": "CA",
        "county": "San Bernardino County",
        "population": 222101,
        "lat": 34.1083,
        "lng": -117.2898,
        "metro_area": "Riverside-San Bernardino-Ontario Metropolitan Area",
        "region": "Inland Empire"
    },
    "modesto": {
        "name": "Modesto",
        "state": "California",
        "state_abbr": "CA",
        "county": "Stanislaus County",
        "population": 218464,
        "lat": 37.6391,
        "lng": -120.9969,
        "metro_area": "Modesto Metropolitan Area",
        "region": "Central Valley"
    },
    "fontana": {
        "name": "Fontana",
        "state": "California",
        "state_abbr": "CA",
        "county": "San Bernardino County", 
        "population": 208393,
        "lat": 34.0922,
        "lng": -117.4350,
        "metro_area": "Riverside-San Bernardino-Ontario Metropolitan Area",
        "region": "Inland Empire"
    },
    "santa-clarita": {
        "name": "Santa Clarita",
        "state": "California",
        "state_abbr": "CA",
        "county": "Los Angeles County",
        "population": 228673,
        "lat": 34.3917,
        "lng": -118.5426,
        "metro_area": "Los Angeles-Long Beach-Anaheim Metropolitan Area",
        "region": "Southern California"
    },

    # TEXAS - Top 20 Cities
    "houston": {
        "name": "Houston",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Harris County",
        "population": 2390125,
        "lat": 29.7604,
        "lng": -95.3698,
        "metro_area": "Houston-The Woodlands-Sugar Land Metropolitan Area",
        "region": "Gulf Coast"
    },
    "san-antonio": {
        "name": "San Antonio", 
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Bexar County",
        "population": 1526656,
        "lat": 29.4241,
        "lng": -98.4936,
        "metro_area": "San Antonio-New Braunfels Metropolitan Area",
        "region": "South Texas"
    },
    "dallas": {
        "name": "Dallas",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Dallas County",
        "population": 1326087,
        "lat": 32.7767,
        "lng": -96.7970,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area",
        "region": "North Texas"
    },
    "fort-worth": {
        "name": "Fort Worth",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Tarrant County",
        "population": 1008106,
        "lat": 32.7555,
        "lng": -97.3308,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area",
        "region": "North Texas"
    },
    "austin": {
        "name": "Austin",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Travis County",
        "population": 993588,
        "lat": 30.2672,
        "lng": -97.7431,
        "metro_area": "Austin-Round Rock-Georgetown Metropolitan Area",
        "region": "Central Texas"
    },
    "el-paso": {
        "name": "El Paso",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "El Paso County",
        "population": 649121,
        "lat": 31.7619,
        "lng": -106.4850,
        "metro_area": "El Paso Metropolitan Area",
        "region": "West Texas"
    },
    "arlington": {
        "name": "Arlington",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Tarrant County",
        "population": 365438,
        "lat": 32.7357,
        "lng": -97.1081,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area",
        "region": "North Texas"
    },
    "corpus-christi": {
        "name": "Corpus Christi",
        "state": "Texas",
        "state_abbr": "TX", 
        "county": "Nueces County",
        "population": 305215,
        "lat": 27.8006,
        "lng": -97.3964,
        "metro_area": "Corpus Christi Metropolitan Area",
        "region": "Coastal Bend"
    },
    "plano": {
        "name": "Plano",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Collin County",
        "population": 259841,
        "lat": 33.0198,
        "lng": -96.6989,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area",
        "region": "North Texas"
    },
    "laredo": {
        "name": "Laredo",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Webb County",
        "population": 236091,
        "lat": 27.5306,
        "lng": -99.4803,
        "metro_area": "Laredo Metropolitan Area",
        "region": "South Texas"
    },
    "lubbock": {
        "name": "Lubbock",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Lubbock County",
        "population": 229573,
        "lat": 33.5779,
        "lng": -101.8552,
        "metro_area": "Lubbock Metropolitan Area",
        "region": "South Plains"
    },
    "garland": {
        "name": "Garland",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Dallas County",
        "population": 243470,
        "lat": 32.9126,
        "lng": -96.6389,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area",
        "region": "North Texas"
    },
    "irving": {
        "name": "Irving",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Dallas County",
        "population": 216290,
        "lat": 32.8140,
        "lng": -96.9489,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area",
        "region": "North Texas"
    },
    "amarillo": {
        "name": "Amarillo",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Potter County",
        "population": 202408,
        "lat": 35.2220,
        "lng": -101.8313,
        "metro_area": "Amarillo Metropolitan Area",
        "region": "Texas Panhandle"
    },
    "grand-prairie": {
        "name": "Grand Prairie",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Dallas County",
        "population": 202134,
        "lat": 32.7460,
        "lng": -96.9978,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area",
        "region": "North Texas"
    },
    "frisco": {
        "name": "Frisco",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Collin County",
        "population": 225007,
        "lat": 33.1507,
        "lng": -96.8236,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area",
        "region": "North Texas"
    },
    "mckinney": {
        "name": "McKinney",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Collin County",
        "population": 213509,
        "lat": 33.1972,
        "lng": -96.6153,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area", 
        "region": "North Texas"
    },
    "brownsville": {
        "name": "Brownsville",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Cameron County",
        "population": 190158,
        "lat": 25.9018,
        "lng": -97.4975,
        "metro_area": "Brownsville-Harlingen Metropolitan Area",
        "region": "Rio Grande Valley"
    },
    "pasadena": {
        "name": "Pasadena",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Harris County",
        "population": 146716,
        "lat": 29.6911,
        "lng": -95.2091,
        "metro_area": "Houston-The Woodlands-Sugar Land Metropolitan Area",
        "region": "Gulf Coast"
    },
    "mesquite": {
        "name": "Mesquite",
        "state": "Texas",
        "state_abbr": "TX",
        "county": "Dallas County",
        "population": 147317,
        "lat": 32.7668,
        "lng": -96.5992,
        "metro_area": "Dallas-Fort Worth-Arlington Metropolitan Area",
        "region": "North Texas"
    },

    # ARIZONA - Top 20 Cities
    "phoenix": {
        "name": "Phoenix",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 1650070,
        "lat": 33.4484,
        "lng": -112.0740,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "tucson": {
        "name": "Tucson",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Pima County",
        "population": 547239,
        "lat": 32.2226,
        "lng": -110.9747,
        "metro_area": "Tucson Metropolitan Area",
        "region": "Southern Arizona"
    },
    "mesa": {
        "name": "Mesa",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 511648,
        "lat": 33.4152,
        "lng": -111.8315,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "chandler": {
        "name": "Chandler",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 280167,
        "lat": 33.3062,
        "lng": -111.8413,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "gilbert": {
        "name": "Gilbert",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 275411,
        "lat": 33.3528,
        "lng": -111.7890,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "glendale": {
        "name": "Glendale",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 252136,
        "lat": 33.5387,
        "lng": -112.1860,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "scottsdale": {
        "name": "Scottsdale",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 243050,
        "lat": 33.4942,
        "lng": -111.9261,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "peoria": {
        "name": "Peoria",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 197866,
        "lat": 33.5806,
        "lng": -112.2374,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "tempe": {
        "name": "Tempe",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 185950,
        "lat": 33.4255,
        "lng": -111.9400,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "surprise": {
        "name": "Surprise",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 147965,
        "lat": 33.6292,
        "lng": -112.3679,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "yuma": {
        "name": "Yuma",
        "state": "Arizona", 
        "state_abbr": "AZ",
        "county": "Yuma County",
        "population": 99559,
        "lat": 32.6927,
        "lng": -114.6277,
        "metro_area": "Yuma Metropolitan Area",
        "region": "Southwestern Arizona"
    },
    "avondale": {
        "name": "Avondale",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 89334,
        "lat": 33.4356,
        "lng": -112.3496,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "flagstaff": {
        "name": "Flagstaff",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Coconino County",
        "population": 79023,
        "lat": 35.1983,
        "lng": -111.6513,
        "metro_area": "Flagstaff Metropolitan Area",
        "region": "Northern Arizona"
    },
    "goodyear": {
        "name": "Goodyear",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 95294,
        "lat": 33.4355,
        "lng": -112.3576,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "buckeye": {
        "name": "Buckeye",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Maricopa County",
        "population": 91502,
        "lat": 33.3703,
        "lng": -112.5838,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "casa-grande": {
        "name": "Casa Grande",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Pinal County",
        "population": 63684,
        "lat": 32.8795,
        "lng": -111.7574,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "sierra-vista": {
        "name": "Sierra Vista",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Cochise County",
        "population": 45308,
        "lat": 31.5455,
        "lng": -110.3032,
        "metro_area": "Sierra Vista-Douglas Metropolitan Area",
        "region": "Southeastern Arizona"
    },
    "maricopa": {
        "name": "Maricopa",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Pinal County",
        "population": 66290,
        "lat": 33.0581,
        "lng": -112.0476,
        "metro_area": "Phoenix-Mesa-Scottsdale Metropolitan Area",
        "region": "Central Arizona"
    },
    "lake-havasu-city": {
        "name": "Lake Havasu City",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Mohave County",
        "population": 57144,
        "lat": 34.4839,
        "lng": -114.3227,
        "metro_area": "Lake Havasu City-Kingman Metropolitan Area",
        "region": "Northwestern Arizona"
    },
    "oro-valley": {
        "name": "Oro Valley",
        "state": "Arizona",
        "state_abbr": "AZ",
        "county": "Pima County",
        "population": 47070,
        "lat": 32.3909,
        "lng": -110.9665,
        "metro_area": "Tucson Metropolitan Area",
        "region": "Southern Arizona"
    },

    # NEVADA - Top 20 Cities  
    "las-vegas": {
        "name": "Las Vegas",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Clark County",
        "population": 670352,
        "lat": 36.1699,
        "lng": -115.1398,
        "metro_area": "Las Vegas-Henderson-Paradise Metropolitan Area",
        "region": "Southern Nevada"
    },
    "henderson": {
        "name": "Henderson",
        "state": "Nevada",
        "state_abbr": "NV", 
        "county": "Clark County",
        "population": 337305,
        "lat": 36.0397,
        "lng": -114.9817,
        "metro_area": "Las Vegas-Henderson-Paradise Metropolitan Area",
        "region": "Southern Nevada"
    },
    "reno": {
        "name": "Reno",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Washoe County",
        "population": 274915,
        "lat": 39.5296,
        "lng": -119.8138,
        "metro_area": "Reno-Sparks Metropolitan Area",
        "region": "Northern Nevada"
    },
    "north-las-vegas": {
        "name": "North Las Vegas",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Clark County",
        "population": 284771,
        "lat": 36.1989,
        "lng": -115.1175,
        "metro_area": "Las Vegas-Henderson-Paradise Metropolitan Area",
        "region": "Southern Nevada"
    },
    "sparks": {
        "name": "Sparks",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Washoe County",
        "population": 108445,
        "lat": 39.5349,
        "lng": -119.7527,
        "metro_area": "Reno-Sparks Metropolitan Area",
        "region": "Northern Nevada"
    },
    "carson-city": {
        "name": "Carson City",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Carson City (Independent City)",
        "population": 58639,
        "lat": 39.1638,
        "lng": -119.7674,
        "metro_area": "Carson City Metropolitan Area",
        "region": "Northern Nevada"
    },
    "fernley": {
        "name": "Fernley",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Lyon County", 
        "population": 22895,
        "lat": 39.6077,
        "lng": -119.2518,
        "metro_area": "Reno-Sparks Metropolitan Area",
        "region": "Northern Nevada"
    },
    "elko": {
        "name": "Elko",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Elko County",
        "population": 20564,
        "lat": 40.8324,
        "lng": -115.7631,
        "metro_area": "Elko Micropolitan Area",
        "region": "Northeastern Nevada"
    },
    "mesquite": {
        "name": "Mesquite",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Clark County",
        "population": 20471,
        "lat": 36.8055,
        "lng": -114.0719,
        "metro_area": "Las Vegas-Henderson-Paradise Metropolitan Area",
        "region": "Southern Nevada"
    },
    "boulder-city": {
        "name": "Boulder City",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Clark County",
        "population": 14885,
        "lat": 35.9722,
        "lng": -114.8327,
        "metro_area": "Las Vegas-Henderson-Paradise Metropolitan Area",
        "region": "Southern Nevada"
    },
    "minden": {
        "name": "Minden",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Douglas County",
        "population": 3001,
        "lat": 38.9541,
        "lng": -119.7657,
        "metro_area": "Carson City Metropolitan Area",
        "region": "Northern Nevada"
    },
    "gardnerville": {
        "name": "Gardnerville",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Douglas County",
        "population": 6211,
        "lat": 38.9413,
        "lng": -119.7490,
        "metro_area": "Carson City Metropolitan Area",
        "region": "Northern Nevada"
    },
    "fallon": {
        "name": "Fallon",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Churchill County",
        "population": 9327,
        "lat": 39.4735,
        "lng": -118.7774,
        "metro_area": "Fallon Micropolitan Area",
        "region": "Central Nevada"
    },
    "yerington": {
        "name": "Yerington",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Lyon County",
        "population": 3145,
        "lat": 38.9874,
        "lng": -119.1638,
        "metro_area": "Carson City Metropolitan Area",
        "region": "Northern Nevada"
    },
    "winnemucca": {
        "name": "Winnemucca",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Humboldt County",
        "population": 8431,
        "lat": 40.9729,
        "lng": -117.7357,
        "metro_area": "Winnemucca Micropolitan Area",
        "region": "Northern Nevada"
    },
    "west-wendover": {
        "name": "West Wendover",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Elko County",
        "population": 4512,
        "lat": 40.7391,
        "lng": -114.0733,
        "metro_area": "Elko Micropolitan Area", 
        "region": "Northeastern Nevada"
    },
    "ely": {
        "name": "Ely",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "White Pine County",
        "population": 3993,
        "lat": 39.2474,
        "lng": -114.8886,
        "metro_area": "Ely Micropolitan Area",
        "region": "Eastern Nevada"
    },
    "carlin": {
        "name": "Carlin",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Elko County",
        "population": 2368,
        "lat": 40.7135,
        "lng": -116.1069,
        "metro_area": "Elko Micropolitan Area",
        "region": "Northeastern Nevada"
    },
    "lovelock": {
        "name": "Lovelock",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Pershing County",
        "population": 1867,
        "lat": 40.1791,
        "lng": -118.4732,
        "metro_area": "Lovelock Micropolitan Area",
        "region": "Northern Nevada"
    },
    "wells": {
        "name": "Wells",
        "state": "Nevada",
        "state_abbr": "NV",
        "county": "Elko County",
        "population": 1292,
        "lat": 41.1107,
        "lng": -114.9636,
        "metro_area": "Elko Micropolitan Area",
        "region": "Northeastern Nevada"
    },

    # OREGON - Top 20 Cities
    "portland": {
        "name": "Portland",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Multnomah County",
        "population": 652503,
        "lat": 45.5152,
        "lng": -122.6784,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "salem": {
        "name": "Salem",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Marion County",
        "population": 178302,
        "lat": 44.9429,
        "lng": -123.0351,
        "metro_area": "Salem Metropolitan Area",
        "region": "Willamette Valley"
    },
    "eugene": {
        "name": "Eugene",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Lane County",
        "population": 177723,
        "lat": 44.0521,
        "lng": -123.0868,
        "metro_area": "Eugene-Springfield Metropolitan Area",
        "region": "Willamette Valley"
    },
    "gresham": {
        "name": "Gresham",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Multnomah County",
        "population": 114247,
        "lat": 45.5001,
        "lng": -122.4302,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "hillsboro": {
        "name": "Hillsboro",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Washington County",
        "population": 106633,
        "lat": 45.5228,
        "lng": -122.9892,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "bend": {
        "name": "Bend",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Deschutes County",
        "population": 103485,
        "lat": 44.0582,
        "lng": -121.3153,
        "metro_area": "Bend Metropolitan Area",
        "region": "Central Oregon"
    },
    "beaverton": {
        "name": "Beaverton",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Washington County",
        "population": 98962,
        "lat": 45.4871,
        "lng": -122.8037,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "medford": {
        "name": "Medford",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Jackson County",
        "population": 85824,
        "lat": 42.3265,
        "lng": -122.8756,
        "metro_area": "Medford Metropolitan Area",
        "region": "Southern Oregon"
    },
    "springfield": {
        "name": "Springfield",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Lane County",
        "population": 64126,
        "lat": 44.0462,
        "lng": -123.0220,
        "metro_area": "Eugene-Springfield Metropolitan Area",
        "region": "Willamette Valley"
    },
    "corvallis": {
        "name": "Corvallis",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Benton County",
        "population": 59922,
        "lat": 44.5646,
        "lng": -123.2620,
        "metro_area": "Corvallis Metropolitan Area",
        "region": "Willamette Valley"
    },
    "albany": {
        "name": "Albany",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Linn County",
        "population": 57705,
        "lat": 44.6365,
        "lng": -123.1059,
        "metro_area": "Albany-Lebanon Metropolitan Area",
        "region": "Willamette Valley"
    },
    "tigard": {
        "name": "Tigard",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Washington County",
        "population": 57690,
        "lat": 45.4312,
        "lng": -122.7715,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "lake-oswego": {
        "name": "Lake Oswego",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Clackamas County",
        "population": 40731,
        "lat": 45.4207,
        "lng": -122.6709,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "kenosha": {
        "name": "Kenosha",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Clackamas County",
        "population": 43442,
        "lat": 45.3596,
        "lng": -122.5893,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "grants-pass": {
        "name": "Grants Pass",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Josephine County",
        "population": 38865,
        "lat": 42.4390,
        "lng": -123.3307,
        "metro_area": "Grants Pass Metropolitan Area",
        "region": "Southern Oregon"
    },
    "oregon-city": {
        "name": "Oregon City",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Clackamas County",
        "population": 37710,
        "lat": 45.3573,
        "lng": -122.6068,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "mcminnville": {
        "name": "McMinnville",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Yamhill County",
        "population": 34319,
        "lat": 45.2104,
        "lng": -123.1987,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "redmond": {
        "name": "Redmond",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Deschutes County",
        "population": 33274,
        "lat": 44.2721,
        "lng": -121.1736,
        "metro_area": "Bend Metropolitan Area",
        "region": "Central Oregon"
    },
    "tualatin": {
        "name": "Tualatin",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Washington County",
        "population": 27942,
        "lat": 45.3840,
        "lng": -122.7637,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },
    "west-linn": {
        "name": "West Linn",
        "state": "Oregon",
        "state_abbr": "OR",
        "county": "Clackamas County",
        "population": 26767,
        "lat": 45.3662,
        "lng": -122.6123,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Northwestern Oregon"
    },

    # WASHINGTON - Top 20 Cities
    "seattle": {
        "name": "Seattle",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "King County",
        "population": 749256,
        "lat": 47.6062,
        "lng": -122.3321,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "spokane": {
        "name": "Spokane",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Spokane County",
        "population": 230176,
        "lat": 47.6587,
        "lng": -117.4260,
        "metro_area": "Spokane-Spokane Valley Metropolitan Area",
        "region": "Eastern Washington"
    },
    "tacoma": {
        "name": "Tacoma",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Pierce County",
        "population": 219346,
        "lat": 47.2529,
        "lng": -122.4443,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "vancouver": {
        "name": "Vancouver",
        "state": "Washington", 
        "state_abbr": "WA",
        "county": "Clark County",
        "population": 190915,
        "lat": 45.6387,
        "lng": -122.6615,
        "metro_area": "Portland-Vancouver-Hillsboro Metropolitan Area",
        "region": "Southwestern Washington"
    },
    "bellevue": {
        "name": "Bellevue",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "King County",
        "population": 151854,
        "lat": 47.6101,
        "lng": -122.2015,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "kent": {
        "name": "Kent",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "King County",
        "population": 136588,
        "lat": 47.3809,
        "lng": -122.2348,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "everett": {
        "name": "Everett",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Snohomish County",
        "population": 113806,
        "lat": 47.9790,
        "lng": -122.2021,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "renton": {
        "name": "Renton",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "King County", 
        "population": 106785,
        "lat": 47.4829,
        "lng": -122.2171,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "spokane-valley": {
        "name": "Spokane Valley",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Spokane County",
        "population": 102976,
        "lat": 47.6732,
        "lng": -117.2394,
        "metro_area": "Spokane-Spokane Valley Metropolitan Area",
        "region": "Eastern Washington"
    },
    "federal-way": {
        "name": "Federal Way",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "King County",
        "population": 100252,
        "lat": 47.3223,
        "lng": -122.3126,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "yakima": {
        "name": "Yakima",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Yakima County",
        "population": 96968,
        "lat": 46.6021,
        "lng": -120.5059,
        "metro_area": "Yakima Metropolitan Area",
        "region": "Central Washington"
    },
    "bellingham": {
        "name": "Bellingham",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Whatcom County",
        "population": 91482,
        "lat": 48.7519,
        "lng": -122.4787,
        "metro_area": "Bellingham Metropolitan Area",
        "region": "Northwestern Washington"
    },
    "kennewick": {
        "name": "Kennewick",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Benton County",
        "population": 84347,
        "lat": 46.2112,
        "lng": -119.1372,
        "metro_area": "Tri-Cities Metropolitan Area",
        "region": "Southeastern Washington"
    },
    "auburn": {
        "name": "Auburn",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "King County",
        "population": 87256,
        "lat": 47.3074,
        "lng": -122.2284,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "pasco": {
        "name": "Pasco",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Franklin County",
        "population": 80064,
        "lat": 46.2396,
        "lng": -119.1006,
        "metro_area": "Tri-Cities Metropolitan Area", 
        "region": "Southeastern Washington"
    },
    "marysville": {
        "name": "Marysville",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Snohomish County",
        "population": 70714,
        "lat": 48.0518,
        "lng": -122.1771,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "lakewood": {
        "name": "Lakewood",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Pierce County",
        "population": 63612,
        "lat": 47.1717,
        "lng": -122.5185,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "redmond": {
        "name": "Redmond",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "King County",
        "population": 73256,
        "lat": 47.6740,
        "lng": -122.1215,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },
    "richland": {
        "name": "Richland",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "Benton County",
        "population": 60560,
        "lat": 46.2857,
        "lng": -119.2845,
        "metro_area": "Tri-Cities Metropolitan Area",
        "region": "Southeastern Washington"
    },
    "kirkland": {
        "name": "Kirkland",
        "state": "Washington",
        "state_abbr": "WA",
        "county": "King County",
        "population": 92175,
        "lat": 47.6815,
        "lng": -122.2087,
        "metro_area": "Seattle-Tacoma-Bellevue Metropolitan Area",
        "region": "Puget Sound"
    },

    # UTAH - Top 20 Cities
    "salt-lake-city": {
        "name": "Salt Lake City",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Salt Lake County",
        "population": 200133,
        "lat": 40.7608,
        "lng": -111.8911,
        "metro_area": "Salt Lake City Metropolitan Area",
        "region": "Northern Utah"
    },
    "west-valley-city": {
        "name": "West Valley City",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Salt Lake County",
        "population": 140230,
        "lat": 40.6916,
        "lng": -112.0011,
        "metro_area": "Salt Lake City Metropolitan Area",
        "region": "Northern Utah"
    },
    "provo": {
        "name": "Provo",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Utah County",
        "population": 115162,
        "lat": 40.2338,
        "lng": -111.6585,
        "metro_area": "Provo-Orem Metropolitan Area",
        "region": "Northern Utah"
    },
    "west-jordan": {
        "name": "West Jordan",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Salt Lake County",
        "population": 116961,
        "lat": 40.6097,
        "lng": -111.9391,
        "metro_area": "Salt Lake City Metropolitan Area",
        "region": "Northern Utah"
    },
    "orem": {
        "name": "Orem",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Utah County",
        "population": 98129,
        "lat": 40.2969,
        "lng": -111.6946,
        "metro_area": "Provo-Orem Metropolitan Area",
        "region": "Northern Utah"
    },
    "sandy": {
        "name": "Sandy",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Salt Lake County",
        "population": 96904,
        "lat": 40.5649,
        "lng": -111.8389,
        "metro_area": "Salt Lake City Metropolitan Area",
        "region": "Northern Utah"
    },
    "ogden": {
        "name": "Ogden",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Weber County",
        "population": 87321,
        "lat": 41.2230,
        "lng": -111.9738,
        "metro_area": "Ogden-Clearfield Metropolitan Area",
        "region": "Northern Utah"
    },
    "st-george": {
        "name": "St. George",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Washington County",
        "population": 95342,
        "lat": 37.0965,
        "lng": -113.5684,
        "metro_area": "St. George Metropolitan Area",
        "region": "Southern Utah"
    },
    "layton": {
        "name": "Layton",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Davis County",
        "population": 81773,
        "lat": 41.0602,
        "lng": -111.9711,
        "metro_area": "Ogden-Clearfield Metropolitan Area",
        "region": "Northern Utah"
    },
    "millcreek": {
        "name": "Millcreek",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Salt Lake County",
        "population": 63380,
        "lat": 40.6869,
        "lng": -111.8158,
        "metro_area": "Salt Lake City Metropolitan Area",
        "region": "Northern Utah"
    },
    "taylorsville": {
        "name": "Taylorsville",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Salt Lake County",
        "population": 60448,
        "lat": 40.6677,
        "lng": -111.9388,
        "metro_area": "Salt Lake City Metropolitan Area",
        "region": "Northern Utah"
    },
    "south-jordan": {
        "name": "South Jordan",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Salt Lake County",
        "population": 77487,
        "lat": 40.5622,
        "lng": -111.9296,
        "metro_area": "Salt Lake City Metropolitan Area",
        "region": "Northern Utah"
    },
    "lehi": {
        "name": "Lehi",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Utah County",
        "population": 75907,
        "lat": 40.3916,
        "lng": -111.8508,
        "metro_area": "Provo-Orem Metropolitan Area",
        "region": "Northern Utah"
    },
    "logan": {
        "name": "Logan",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Cache County",
        "population": 52778,
        "lat": 41.7370,
        "lng": -111.8338,
        "metro_area": "Logan Metropolitan Area",
        "region": "Northern Utah"
    },
    "spanish-fork": {
        "name": "Spanish Fork",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Utah County",
        "population": 42602,
        "lat": 40.1149,
        "lng": -111.6549,
        "metro_area": "Provo-Orem Metropolitan Area",
        "region": "Northern Utah"
    },
    "springville": {
        "name": "Springville",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Utah County",
        "population": 35268,
        "lat": 40.1652,
        "lng": -111.6091,
        "metro_area": "Provo-Orem Metropolitan Area",
        "region": "Northern Utah"
    },
    "murray": {
        "name": "Murray",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Salt Lake County",
        "population": 50637,
        "lat": 40.6669,
        "lng": -111.8880,
        "metro_area": "Salt Lake City Metropolitan Area",
        "region": "Northern Utah"
    },
    "pleasant-grove": {
        "name": "Pleasant Grove",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Utah County",
        "population": 37726,
        "lat": 40.3641,
        "lng": -111.7385,
        "metro_area": "Provo-Orem Metropolitan Area",
        "region": "Northern Utah"
    },
    "tooele": {
        "name": "Tooele",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Tooele County",
        "population": 35742,
        "lat": 40.5307,
        "lng": -112.2983,
        "metro_area": "Salt Lake City Metropolitan Area",
        "region": "Northern Utah"
    },
    "roy": {
        "name": "Roy",
        "state": "Utah",
        "state_abbr": "UT",
        "county": "Weber County",
        "population": 39243,
        "lat": 41.1616,
        "lng": -112.0263,
        "metro_area": "Ogden-Clearfield Metropolitan Area",
        "region": "Northern Utah"
    },

    # COLORADO - Top 20 Cities
    "denver": {
        "name": "Denver",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Denver County",
        "population": 715522,
        "lat": 39.7392,
        "lng": -104.9903,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "colorado-springs": {
        "name": "Colorado Springs",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "El Paso County",
        "population": 478961,
        "lat": 38.8339,
        "lng": -104.8214,
        "metro_area": "Colorado Springs Metropolitan Area",
        "region": "Front Range"
    },
    "aurora": {
        "name": "Aurora",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Arapahoe County",
        "population": 386261,
        "lat": 39.7294,
        "lng": -104.8319,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "fort-collins": {
        "name": "Fort Collins",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Larimer County",
        "population": 169810,
        "lat": 40.5853,
        "lng": -105.0844,
        "metro_area": "Fort Collins Metropolitan Area",
        "region": "Front Range"
    },
    "lakewood": {
        "name": "Lakewood",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Jefferson County",
        "population": 155984,
        "lat": 39.7047,
        "lng": -105.0814,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "thornton": {
        "name": "Thornton",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Adams County",
        "population": 141867,
        "lat": 39.8681,
        "lng": -104.9719,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "arvada": {
        "name": "Arvada",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Jefferson County",
        "population": 124402,
        "lat": 39.8028,
        "lng": -105.0875,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "westminster": {
        "name": "Westminster",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Adams County",
        "population": 116317,
        "lat": 39.8367,
        "lng": -105.0372,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "pueblo": {
        "name": "Pueblo",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Pueblo County",
        "population": 111876,
        "lat": 38.2544,
        "lng": -104.6091,
        "metro_area": "Pueblo Metropolitan Area",
        "region": "South Central Colorado"
    },
    "centennial": {
        "name": "Centennial",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Arapahoe County",
        "population": 108418,
        "lat": 39.5807,
        "lng": -104.8756,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "boulder": {
        "name": "Boulder",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Boulder County",
        "population": 108250,
        "lat": 40.0150,
        "lng": -105.2705,
        "metro_area": "Boulder Metropolitan Area",
        "region": "Front Range"
    },
    "greeley": {
        "name": "Greeley",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Weld County",
        "population": 108795,
        "lat": 40.4233,
        "lng": -104.7091,
        "metro_area": "Greeley Metropolitan Area",
        "region": "Front Range"
    },
    "longmont": {
        "name": "Longmont",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Boulder County",
        "population": 98885,
        "lat": 40.1672,
        "lng": -105.1019,
        "metro_area": "Boulder Metropolitan Area",
        "region": "Front Range"
    },
    "loveland": {
        "name": "Loveland",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Larimer County",
        "population": 76378,
        "lat": 40.3978,
        "lng": -105.0750,
        "metro_area": "Fort Collins Metropolitan Area",
        "region": "Front Range"
    },
    "grand-junction": {
        "name": "Grand Junction",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Mesa County",
        "population": 65560,
        "lat": 39.0639,
        "lng": -108.5506,
        "metro_area": "Grand Junction Metropolitan Area",
        "region": "Western Colorado"
    },
    "broomfield": {
        "name": "Broomfield",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Broomfield County",
        "population": 74112,
        "lat": 39.9205,
        "lng": -105.0866,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "castle-rock": {
        "name": "Castle Rock",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Douglas County",
        "population": 73158,
        "lat": 39.3722,
        "lng": -104.8561,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "commerce-city": {
        "name": "Commerce City",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Adams County",
        "population": 62418,
        "lat": 39.8083,
        "lng": -104.9339,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "parker": {
        "name": "Parker",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Douglas County",
        "population": 58512,
        "lat": 39.5186,
        "lng": -104.7617,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },
    "wheat-ridge": {
        "name": "Wheat Ridge",
        "state": "Colorado",
        "state_abbr": "CO",
        "county": "Jefferson County",
        "population": 31889,
        "lat": 39.7661,
        "lng": -105.0772,
        "metro_area": "Denver-Aurora-Lakewood Metropolitan Area",
        "region": "Front Range"
    },

    # NEW MEXICO - Top 20 Cities
    "albuquerque": {
        "name": "Albuquerque",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Bernalillo County",
        "population": 564559,
        "lat": 35.0844,
        "lng": -106.6504,
        "metro_area": "Albuquerque Metropolitan Area",
        "region": "Central New Mexico"
    },
    "las-cruces": {
        "name": "Las Cruces",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Doña Ana County",
        "population": 111385,
        "lat": 32.3199,
        "lng": -106.7637,
        "metro_area": "Las Cruces Metropolitan Area",
        "region": "Southern New Mexico"
    },
    "rio-rancho": {
        "name": "Rio Rancho",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Sandoval County",
        "population": 104046,
        "lat": 35.2328,
        "lng": -106.6630,
        "metro_area": "Albuquerque Metropolitan Area",
        "region": "Central New Mexico"
    },
    "santa-fe": {
        "name": "Santa Fe",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Santa Fe County",
        "population": 87505,
        "lat": 35.6870,
        "lng": -105.9378,
        "metro_area": "Santa Fe Metropolitan Area",
        "region": "Northern New Mexico"
    },
    "roswell": {
        "name": "Roswell",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Chaves County",
        "population": 48422,
        "lat": 33.3943,
        "lng": -104.5230,
        "metro_area": "Roswell Micropolitan Area",
        "region": "Southeastern New Mexico"
    },
    "farmington": {
        "name": "Farmington",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "San Juan County",
        "population": 45877,
        "lat": 36.7281,
        "lng": -108.2187,
        "metro_area": "Farmington Metropolitan Area",
        "region": "Northwestern New Mexico"
    },
    "clovis": {
        "name": "Clovis",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Curry County",
        "population": 38567,
        "lat": 34.4048,
        "lng": -103.2052,
        "metro_area": "Clovis Micropolitan Area",
        "region": "Eastern New Mexico"
    },
    "hobbs": {
        "name": "Hobbs",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Lea County",
        "population": 38475,
        "lat": 32.7023,
        "lng": -103.1360,
        "metro_area": "Hobbs Micropolitan Area",
        "region": "Southeastern New Mexico"
    },
    "alamogordo": {
        "name": "Alamogordo",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Otero County",
        "population": 31384,
        "lat": 32.8995,
        "lng": -105.9603,
        "metro_area": "Alamogordo Micropolitan Area",
        "region": "South Central New Mexico"
    },
    "carlsbad": {
        "name": "Carlsbad",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Eddy County",
        "population": 32238,
        "lat": 32.4207,
        "lng": -104.2288,
        "metro_area": "Carlsbad-Artesia Micropolitan Area",
        "region": "Southeastern New Mexico"
    },
    "gallup": {
        "name": "Gallup",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "McKinley County",
        "population": 22579,
        "lat": 35.5281,
        "lng": -108.7426,
        "metro_area": "Gallup Micropolitan Area",
        "region": "Northwestern New Mexico"
    },
    "los-alamos": {
        "name": "Los Alamos",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Los Alamos County",
        "population": 13179,
        "lat": 35.8911,
        "lng": -106.2978,
        "metro_area": "Los Alamos Micropolitan Area",
        "region": "Northern New Mexico"
    },
    "chaparral": {
        "name": "Chaparral",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Doña Ana County",
        "population": 14631,
        "lat": 32.0287,
        "lng": -106.3861,
        "metro_area": "Las Cruces Metropolitan Area",
        "region": "Southern New Mexico"
    },
    "sunland-park": {
        "name": "Sunland Park",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Doña Ana County",
        "population": 17581,
        "lat": 31.7965,
        "lng": -106.5806,
        "metro_area": "Las Cruces Metropolitan Area",
        "region": "Southern New Mexico"
    },
    "las-vegas": {
        "name": "Las Vegas",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "San Miguel County",
        "population": 13055,
        "lat": 35.5939,
        "lng": -105.2239,
        "metro_area": "Las Vegas Micropolitan Area",
        "region": "Northern New Mexico"
    },
    "deming": {
        "name": "Deming",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Luna County",
        "population": 14855,
        "lat": 32.2687,
        "lng": -107.7586,
        "metro_area": "Deming Micropolitan Area",
        "region": "Southwestern New Mexico"
    },
    "anthony": {
        "name": "Anthony",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Doña Ana County",
        "population": 9360,
        "lat": 31.9948,
        "lng": -106.5986,
        "metro_area": "Las Cruces Metropolitan Area",
        "region": "Southern New Mexico"
    },
    "artesia": {
        "name": "Artesia",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Eddy County",
        "population": 12875,
        "lat": 32.8423,
        "lng": -104.4058,
        "metro_area": "Carlsbad-Artesia Micropolitan Area",
        "region": "Southeastern New Mexico"
    },
    "portales": {
        "name": "Portales",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Roosevelt County",
        "population": 12280,
        "lat": 34.1862,
        "lng": -103.3324,
        "metro_area": "Portales Micropolitan Area",
        "region": "Eastern New Mexico"
    },
    "lovington": {
        "name": "Lovington",
        "state": "New Mexico",
        "state_abbr": "NM",
        "county": "Lea County",
        "population": 11009,
        "lat": 32.9448,
        "lng": -103.3480,
        "metro_area": "Hobbs Micropolitan Area",
        "region": "Southeastern New Mexico"
    },

    # IDAHO - Top 20 Cities
    "boise": {
        "name": "Boise",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Ada County",
        "population": 235684,
        "lat": 43.6150,
        "lng": -116.2023,
        "metro_area": "Boise Metropolitan Area",
        "region": "Southwestern Idaho"
    },
    "meridian": {
        "name": "Meridian",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Ada County",
        "population": 114161,
        "lat": 43.6121,
        "lng": -116.3915,
        "metro_area": "Boise Metropolitan Area",
        "region": "Southwestern Idaho"
    },
    "nampa": {
        "name": "Nampa",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Canyon County",
        "population": 100200,
        "lat": 43.5407,
        "lng": -116.5635,
        "metro_area": "Boise Metropolitan Area",
        "region": "Southwestern Idaho"
    },
    "idaho-falls": {
        "name": "Idaho Falls",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Bonneville County",
        "population": 64818,
        "lat": 43.4666,
        "lng": -112.0340,
        "metro_area": "Idaho Falls Metropolitan Area",
        "region": "Eastern Idaho"
    },
    "pocatello": {
        "name": "Pocatello",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Bannock County",
        "population": 56320,
        "lat": 42.8713,
        "lng": -112.4455,
        "metro_area": "Pocatello Metropolitan Area",
        "region": "Southeastern Idaho"
    },
    "caldwell": {
        "name": "Caldwell",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Canyon County",
        "population": 63649,
        "lat": 43.6629,
        "lng": -116.6873,
        "metro_area": "Boise Metropolitan Area",
        "region": "Southwestern Idaho"
    },
    "coeur-d-alene": {
        "name": "Coeur d'Alene",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Kootenai County",
        "population": 54628,
        "lat": 47.6777,
        "lng": -116.7804,
        "metro_area": "Coeur d'Alene Metropolitan Area",
        "region": "Northern Idaho"
    },
    "twin-falls": {
        "name": "Twin Falls",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Twin Falls County",
        "population": 51807,
        "lat": 42.5630,
        "lng": -114.4609,
        "metro_area": "Twin Falls Metropolitan Area",
        "region": "South Central Idaho"
    },
    "lewiston": {
        "name": "Lewiston",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Nez Perce County",
        "population": 34203,
        "lat": 46.4165,
        "lng": -117.0177,
        "metro_area": "Lewiston Metropolitan Area",
        "region": "Northern Idaho"
    },
    "post-falls": {
        "name": "Post Falls",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Kootenai County",
        "population": 38485,
        "lat": 47.7180,
        "lng": -116.9516,
        "metro_area": "Coeur d'Alene Metropolitan Area",
        "region": "Northern Idaho"
    },
    "rexburg": {
        "name": "Rexburg",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Madison County",
        "population": 31657,
        "lat": 43.8260,
        "lng": -111.7897,
        "metro_area": "Rexburg Metropolitan Area",
        "region": "Eastern Idaho"
    },
    "moscow": {
        "name": "Moscow",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Latah County",
        "population": 25435,
        "lat": 46.7324,
        "lng": -117.0002,
        "metro_area": "Moscow Micropolitan Area",
        "region": "Northern Idaho"
    },
    "hayden": {
        "name": "Hayden",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Kootenai County",
        "population": 15570,
        "lat": 47.7660,
        "lng": -116.7865,
        "metro_area": "Coeur d'Alene Metropolitan Area",
        "region": "Northern Idaho"
    },
    "eagle": {
        "name": "Eagle",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Ada County",
        "population": 30346,
        "lat": 43.6966,
        "lng": -116.3537,
        "metro_area": "Boise Metropolitan Area",
        "region": "Southwestern Idaho"
    },
    "kuna": {
        "name": "Kuna",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Ada County",
        "population": 24011,
        "lat": 43.4907,
        "lng": -116.4201,
        "metro_area": "Boise Metropolitan Area",
        "region": "Southwestern Idaho"
    },
    "blackfoot": {
        "name": "Blackfoot",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Bingham County",
        "population": 12355,
        "lat": 43.1903,
        "lng": -112.3450,
        "metro_area": "Blackfoot Micropolitan Area",
        "region": "Southeastern Idaho"
    },
    "garden-city": {
        "name": "Garden City",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Ada County",
        "population": 12316,
        "lat": 43.6046,
        "lng": -116.2378,
        "metro_area": "Boise Metropolitan Area",
        "region": "Southwestern Idaho"
    },
    "jerome": {
        "name": "Jerome",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Jerome County",
        "population": 12447,
        "lat": 42.7187,
        "lng": -114.5186,
        "metro_area": "Twin Falls Metropolitan Area",
        "region": "South Central Idaho"
    },
    "burley": {
        "name": "Burley",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Cassia County",
        "population": 11704,
        "lat": 42.5358,
        "lng": -113.7928,
        "metro_area": "Burley Micropolitan Area",
        "region": "South Central Idaho"
    },
    "mountain-home": {
        "name": "Mountain Home",
        "state": "Idaho",
        "state_abbr": "ID",
        "county": "Elmore County",
        "population": 14308,
        "lat": 43.1332,
        "lng": -115.6912,
        "metro_area": "Mountain Home Micropolitan Area",
        "region": "Southwestern Idaho"
    }
}