"""
Additional Cities for Expanded SEO Coverage
Mid-size and smaller cities for comprehensive coverage
"""

ADDITIONAL_CITIES = {
    "california": [
        {"name": "Bakersfield", "slug": "bakersfield", "population": "384145", "county": "Kern County"},
        {"name": "Anaheim", "slug": "anaheim", "population": "346824", "county": "Orange County"},
        {"name": "Santa Ana", "slug": "santa-ana", "population": "310227", "county": "Orange County"},
        {"name": "Riverside", "slug": "riverside", "population": "314998", "county": "Riverside County"},
        {"name": "Stockton", "slug": "stockton", "population": "320804", "county": "San Joaquin County"},
        {"name": "Irvine", "slug": "irvine", "population": "307670", "county": "Orange County"},
        {"name": "Chula Vista", "slug": "chula-vista", "population": "275487", "county": "San Diego County"},
        {"name": "Fremont", "slug": "fremont", "population": "241110", "county": "Alameda County"},
        {"name": "San Bernardino", "slug": "san-bernardino", "population": "222101", "county": "San Bernardino County"},
        {"name": "Modesto", "slug": "modesto", "population": "218464", "county": "Stanislaus County"},
        {"name": "Fontana", "slug": "fontana", "population": "208393", "county": "San Bernardino County"},
        {"name": "Oxnard", "slug": "oxnard", "population": "202063", "county": "Ventura County"},
        {"name": "Moreno Valley", "slug": "moreno-valley", "population": "208634", "county": "Riverside County"},
        {"name": "Glendale", "slug": "glendale-ca", "population": "196543", "county": "Los Angeles County"},
        {"name": "Huntington Beach", "slug": "huntington-beach", "population": "198711", "county": "Orange County"},
        {"name": "Santa Rosa", "slug": "santa-rosa", "population": "178127", "county": "Sonoma County"},
        {"name": "Garden Grove", "slug": "garden-grove", "population": "171949", "county": "Orange County"},
        {"name": "Oceanside", "slug": "oceanside", "population": "174648", "county": "San Diego County"},
        {"name": "Rancho Cucamonga", "slug": "rancho-cucamonga", "population": "174453", "county": "San Bernardino County"},
        {"name": "Santa Clarita", "slug": "santa-clarita", "population": "228673", "county": "Los Angeles County"},
        {"name": "Ontario", "slug": "ontario-ca", "population": "175265", "county": "San Bernardino County"},
        {"name": "Lancaster", "slug": "lancaster-ca", "population": "173516", "county": "Los Angeles County"},
        {"name": "Elk Grove", "slug": "elk-grove", "population": "176124", "county": "Sacramento County"},
        {"name": "Palmdale", "slug": "palmdale", "population": "169450", "county": "Los Angeles County"},
        {"name": "Corona", "slug": "corona", "population": "169868", "county": "Riverside County"},
        {"name": "Salinas", "slug": "salinas", "population": "163542", "county": "Monterey County"},
        {"name": "Pomona", "slug": "pomona", "population": "151713", "county": "Los Angeles County"},
        {"name": "Hayward", "slug": "hayward", "population": "162954", "county": "Alameda County"},
        {"name": "Escondido", "slug": "escondido", "population": "151038", "county": "San Diego County"},
        {"name": "Sunnyvale", "slug": "sunnyvale", "population": "155805", "county": "Santa Clara County"},
        {"name": "Torrance", "slug": "torrance", "population": "147067", "county": "Los Angeles County"},
        {"name": "Roseville", "slug": "roseville-ca", "population": "147773", "county": "Placer County"},
        {"name": "Visalia", "slug": "visalia", "population": "141384", "county": "Tulare County"},
        {"name": "Fullerton", "slug": "fullerton", "population": "143617", "county": "Orange County"},
        {"name": "Orange", "slug": "orange-ca", "population": "139911", "county": "Orange County"},
        {"name": "Pasadena", "slug": "pasadena-ca", "population": "138699", "county": "Los Angeles County"},
        {"name": "Thousand Oaks", "slug": "thousand-oaks", "population": "126966", "county": "Ventura County"},
        {"name": "Concord", "slug": "concord-ca", "population": "129295", "county": "Contra Costa County"},
        {"name": "Simi Valley", "slug": "simi-valley", "population": "126356", "county": "Ventura County"},
        {"name": "Vallejo", "slug": "vallejo", "population": "126090", "county": "Solano County"}
    ],
    "texas": [
        {"name": "Austin", "slug": "austin", "population": "961855", "county": "Travis County"},
        {"name": "Fort Worth", "slug": "fort-worth", "population": "918915", "county": "Tarrant County"},
        {"name": "El Paso", "slug": "el-paso", "population": "678815", "county": "El Paso County"},
        {"name": "Arlington", "slug": "arlington-tx", "population": "394266", "county": "Tarrant County"},
        {"name": "Corpus Christi", "slug": "corpus-christi", "population": "317863", "county": "Nueces County"},
        {"name": "Plano", "slug": "plano", "population": "285494", "county": "Collin County"},
        {"name": "Laredo", "slug": "laredo", "population": "255205", "county": "Webb County"},
        {"name": "Lubbock", "slug": "lubbock", "population": "258862", "county": "Lubbock County"},
        {"name": "Garland", "slug": "garland", "population": "246018", "county": "Dallas County"},
        {"name": "Irving", "slug": "irving", "population": "256684", "county": "Dallas County"},
        {"name": "Amarillo", "slug": "amarillo", "population": "200393", "county": "Potter County"},
        {"name": "Grand Prairie", "slug": "grand-prairie", "population": "196100", "county": "Dallas County"},
        {"name": "McKinney", "slug": "mckinney", "population": "195308", "county": "Collin County"},
        {"name": "Frisco", "slug": "frisco", "population": "200490", "county": "Collin County"},
        {"name": "Brownsville", "slug": "brownsville", "population": "186738", "county": "Cameron County"},
        {"name": "Pasadena", "slug": "pasadena-tx", "population": "151227", "county": "Harris County"},
        {"name": "Mesquite", "slug": "mesquite", "population": "150108", "county": "Dallas County"},
        {"name": "Killeen", "slug": "killeen", "population": "153095", "county": "Bell County"},
        {"name": "McAllen", "slug": "mcallen", "population": "142212", "county": "Hidalgo County"},
        {"name": "Waco", "slug": "waco", "population": "139236", "county": "McLennan County"},
        {"name": "Carrollton", "slug": "carrollton", "population": "133434", "county": "Dallas County"},
        {"name": "Denton", "slug": "denton", "population": "139869", "county": "Denton County"},
        {"name": "Midland", "slug": "midland", "population": "146038", "county": "Midland County"},
        {"name": "Abilene", "slug": "abilene", "population": "125182", "county": "Taylor County"},
        {"name": "Beaumont", "slug": "beaumont", "population": "115282", "county": "Jefferson County"},
        {"name": "Round Rock", "slug": "round-rock", "population": "133372", "county": "Williamson County"},
        {"name": "Richardson", "slug": "richardson", "population": "121323", "county": "Dallas County"},
        {"name": "Wichita Falls", "slug": "wichita-falls", "population": "102316", "county": "Wichita County"},
        {"name": "Odessa", "slug": "odessa", "population": "123334", "county": "Ector County"},
        {"name": "College Station", "slug": "college-station", "population": "120511", "county": "Brazos County"}
    ],
    "florida": [
        {"name": "Jacksonville", "slug": "jacksonville", "population": "949611", "county": "Duval County"},
        {"name": "Miami", "slug": "miami", "population": "442241", "county": "Miami-Dade County"},
        {"name": "Tampa", "slug": "tampa", "population": "384959", "county": "Hillsborough County"},
        {"name": "Orlando", "slug": "orlando", "population": "307573", "county": "Orange County"},
        {"name": "St. Petersburg", "slug": "st-petersburg", "population": "258308", "county": "Pinellas County"},
        {"name": "Hialeah", "slug": "hialeah", "population": "223109", "county": "Miami-Dade County"},
        {"name": "Port St. Lucie", "slug": "port-st-lucie", "population": "204851", "county": "St. Lucie County"},
        {"name": "Cape Coral", "slug": "cape-coral", "population": "194495", "county": "Lee County"},
        {"name": "Tallahassee", "slug": "tallahassee", "population": "194500", "county": "Leon County"},
        {"name": "Fort Lauderdale", "slug": "fort-lauderdale", "population": "182595", "county": "Broward County"},
        {"name": "Pembroke Pines", "slug": "pembroke-pines", "population": "171178", "county": "Broward County"},
        {"name": "Hollywood", "slug": "hollywood-fl", "population": "153067", "county": "Broward County"},
        {"name": "Gainesville", "slug": "gainesville", "population": "141085", "county": "Alachua County"},
        {"name": "Coral Springs", "slug": "coral-springs", "population": "134394", "county": "Broward County"},
        {"name": "Miramar", "slug": "miramar", "population": "134721", "county": "Broward County"},
        {"name": "Clearwater", "slug": "clearwater", "population": "117292", "county": "Pinellas County"},
        {"name": "Palm Bay", "slug": "palm-bay", "population": "119760", "county": "Brevard County"},
        {"name": "West Palm Beach", "slug": "west-palm-beach", "population": "117415", "county": "Palm Beach County"},
        {"name": "Lakeland", "slug": "lakeland", "population": "112641", "county": "Polk County"},
        {"name": "Pompano Beach", "slug": "pompano-beach", "population": "112046", "county": "Broward County"},
        {"name": "Miami Gardens", "slug": "miami-gardens", "population": "111640", "county": "Miami-Dade County"},
        {"name": "Davie", "slug": "davie", "population": "105691", "county": "Broward County"},
        {"name": "Boca Raton", "slug": "boca-raton", "population": "99805", "county": "Palm Beach County"},
        {"name": "Sunrise", "slug": "sunrise", "population": "97335", "county": "Broward County"},
        {"name": "Plantation", "slug": "plantation", "population": "96452", "county": "Broward County"},
        {"name": "Miami Beach", "slug": "miami-beach", "population": "82890", "county": "Miami-Dade County"},
        {"name": "Deltona", "slug": "deltona", "population": "93692", "county": "Volusia County"},
        {"name": "Palm Coast", "slug": "palm-coast", "population": "89258", "county": "Flagler County"},
        {"name": "Deerfield Beach", "slug": "deerfield-beach", "population": "86859", "county": "Broward County"},
        {"name": "Fort Myers", "slug": "fort-myers", "population": "86395", "county": "Lee County"}
    ],
    "illinois": [
        {"name": "Aurora", "slug": "aurora-il", "population": "180542", "county": "Kane County"},
        {"name": "Rockford", "slug": "rockford", "population": "148655", "county": "Winnebago County"},
        {"name": "Joliet", "slug": "joliet", "population": "150362", "county": "Will County"},
        {"name": "Naperville", "slug": "naperville", "population": "149540", "county": "DuPage County"},
        {"name": "Springfield", "slug": "springfield-il", "population": "114394", "county": "Sangamon County"},
        {"name": "Peoria", "slug": "peoria", "population": "113150", "county": "Peoria County"},
        {"name": "Elgin", "slug": "elgin", "population": "114797", "county": "Kane County"},
        {"name": "Waukegan", "slug": "waukegan", "population": "89321", "county": "Lake County"},
        {"name": "Cicero", "slug": "cicero", "population": "85268", "county": "Cook County"},
        {"name": "Champaign", "slug": "champaign", "population": "88909", "county": "Champaign County"},
        {"name": "Bloomington", "slug": "bloomington-il", "population": "78995", "county": "McLean County"},
        {"name": "Decatur", "slug": "decatur-il", "population": "70746", "county": "Macon County"},
        {"name": "Arlington Heights", "slug": "arlington-heights", "population": "77676", "county": "Cook County"},
        {"name": "Evanston", "slug": "evanston", "population": "78110", "county": "Cook County"},
        {"name": "Schaumburg", "slug": "schaumburg", "population": "74907", "county": "Cook County"},
        {"name": "Bolingbrook", "slug": "bolingbrook", "population": "73922", "county": "Will County"},
        {"name": "Palatine", "slug": "palatine", "population": "67908", "county": "Cook County"},
        {"name": "Skokie", "slug": "skokie", "population": "67824", "county": "Cook County"},
        {"name": "Des Plaines", "slug": "des-plaines", "population": "60675", "county": "Cook County"},
        {"name": "Orland Park", "slug": "orland-park", "population": "58703", "county": "Cook County"}
    ],
    "pennsylvania": [
        {"name": "Pittsburgh", "slug": "pittsburgh", "population": "302971", "county": "Allegheny County"},
        {"name": "Allentown", "slug": "allentown", "population": "125845", "county": "Lehigh County"},
        {"name": "Erie", "slug": "erie", "population": "94831", "county": "Erie County"},
        {"name": "Reading", "slug": "reading", "population": "95112", "county": "Berks County"},
        {"name": "Scranton", "slug": "scranton", "population": "76328", "county": "Lackawanna County"},
        {"name": "Bethlehem", "slug": "bethlehem", "population": "75781", "county": "Northampton County"},
        {"name": "Lancaster", "slug": "lancaster-pa", "population": "58039", "county": "Lancaster County"},
        {"name": "Harrisburg", "slug": "harrisburg", "population": "50099", "county": "Dauphin County"},
        {"name": "Altoona", "slug": "altoona", "population": "43963", "county": "Blair County"},
        {"name": "York", "slug": "york-pa", "population": "44800", "county": "York County"},
        {"name": "Wilkes-Barre", "slug": "wilkes-barre", "population": "44328", "county": "Luzerne County"},
        {"name": "Chester", "slug": "chester-pa", "population": "32605", "county": "Delaware County"},
        {"name": "Williamsport", "slug": "williamsport", "population": "27754", "county": "Lycoming County"},
        {"name": "Easton", "slug": "easton", "population": "28127", "county": "Northampton County"},
        {"name": "Lebanon", "slug": "lebanon-pa", "population": "26814", "county": "Lebanon County"},
        {"name": "Hazleton", "slug": "hazleton", "population": "29963", "county": "Luzerne County"},
        {"name": "New Castle", "slug": "new-castle-pa", "population": "21805", "county": "Lawrence County"},
        {"name": "Johnstown", "slug": "johnstown", "population": "18411", "county": "Cambria County"},
        {"name": "McKeesport", "slug": "mckeesport", "population": "17727", "county": "Allegheny County"},
        {"name": "Hermitage", "slug": "hermitage", "population": "15089", "county": "Mercer County"}
    ],
    "ohio": [
        {"name": "Columbus", "slug": "columbus", "population": "905748", "county": "Franklin County"},
        {"name": "Cleveland", "slug": "cleveland", "population": "372624", "county": "Cuyahoga County"},
        {"name": "Cincinnati", "slug": "cincinnati", "population": "309317", "county": "Hamilton County"},
        {"name": "Toledo", "slug": "toledo", "population": "270871", "county": "Lucas County"},
        {"name": "Akron", "slug": "akron", "population": "190469", "county": "Summit County"},
        {"name": "Dayton", "slug": "dayton", "population": "137644", "county": "Montgomery County"},
        {"name": "Parma", "slug": "parma", "population": "81146", "county": "Cuyahoga County"},
        {"name": "Canton", "slug": "canton", "population": "70872", "county": "Stark County"},
        {"name": "Youngstown", "slug": "youngstown", "population": "60068", "county": "Mahoning County"},
        {"name": "Lorain", "slug": "lorain", "population": "65211", "county": "Lorain County"},
        {"name": "Hamilton", "slug": "hamilton-oh", "population": "63399", "county": "Butler County"},
        {"name": "Springfield", "slug": "springfield-oh", "population": "58662", "county": "Clark County"},
        {"name": "Kettering", "slug": "kettering", "population": "57862", "county": "Montgomery County"},
        {"name": "Elyria", "slug": "elyria", "population": "52656", "county": "Lorain County"},
        {"name": "Lakewood", "slug": "lakewood-oh", "population": "50942", "county": "Cuyahoga County"},
        {"name": "Newark", "slug": "newark-oh", "population": "49934", "county": "Licking County"},
        {"name": "Euclid", "slug": "euclid", "population": "49692", "county": "Cuyahoga County"},
        {"name": "Mentor", "slug": "mentor", "population": "47450", "county": "Lake County"},
        {"name": "Beavercreek", "slug": "beavercreek", "population": "46549", "county": "Greene County"},
        {"name": "Strongsville", "slug": "strongsville", "population": "46491", "county": "Cuyahoga County"}
    ],
    "michigan": [
        {"name": "Detroit", "slug": "detroit", "population": "639111", "county": "Wayne County"},
        {"name": "Grand Rapids", "slug": "grand-rapids", "population": "198917", "county": "Kent County"},
        {"name": "Warren", "slug": "warren", "population": "139387", "county": "Macomb County"},
        {"name": "Sterling Heights", "slug": "sterling-heights", "population": "134346", "county": "Macomb County"},
        {"name": "Ann Arbor", "slug": "ann-arbor", "population": "123851", "county": "Washtenaw County"},
        {"name": "Lansing", "slug": "lansing", "population": "112644", "county": "Ingham County"},
        {"name": "Dearborn", "slug": "dearborn", "population": "109976", "county": "Wayne County"},
        {"name": "Livonia", "slug": "livonia", "population": "95535", "county": "Wayne County"},
        {"name": "Troy", "slug": "troy-mi", "population": "87294", "county": "Oakland County"},
        {"name": "Westland", "slug": "westland", "population": "84094", "county": "Wayne County"},
        {"name": "Flint", "slug": "flint", "population": "81252", "county": "Genesee County"},
        {"name": "Farmington Hills", "slug": "farmington-hills", "population": "83986", "county": "Oakland County"},
        {"name": "Kalamazoo", "slug": "kalamazoo", "population": "72873", "county": "Kalamazoo County"},
        {"name": "Wyoming", "slug": "wyoming-mi", "population": "76501", "county": "Kent County"},
        {"name": "Southfield", "slug": "southfield", "population": "76618", "county": "Oakland County"},
        {"name": "Rochester Hills", "slug": "rochester-hills", "population": "76300", "county": "Oakland County"},
        {"name": "Taylor", "slug": "taylor", "population": "63409", "county": "Wayne County"},
        {"name": "St. Clair Shores", "slug": "st-clair-shores", "population": "59184", "county": "Macomb County"},
        {"name": "Pontiac", "slug": "pontiac", "population": "61606", "county": "Oakland County"},
        {"name": "Royal Oak", "slug": "royal-oak", "population": "60062", "county": "Oakland County"}
    ]
}

# Major city neighborhoods/districts for ultra-local SEO
CITY_NEIGHBORHOODS = {
    "new-york-city": [
        {"name": "Manhattan", "slug": "manhattan"},
        {"name": "Brooklyn", "slug": "brooklyn"},
        {"name": "Queens", "slug": "queens"},
        {"name": "Bronx", "slug": "bronx"},
        {"name": "Staten Island", "slug": "staten-island"},
        {"name": "Upper East Side", "slug": "upper-east-side"},
        {"name": "Upper West Side", "slug": "upper-west-side"},
        {"name": "Midtown", "slug": "midtown-manhattan"},
        {"name": "Financial District", "slug": "financial-district"},
        {"name": "Chelsea", "slug": "chelsea"},
        {"name": "Greenwich Village", "slug": "greenwich-village"},
        {"name": "SoHo", "slug": "soho"},
        {"name": "Tribeca", "slug": "tribeca"},
        {"name": "Harlem", "slug": "harlem"},
        {"name": "Williamsburg", "slug": "williamsburg"},
        {"name": "Park Slope", "slug": "park-slope"},
        {"name": "Astoria", "slug": "astoria"},
        {"name": "Flushing", "slug": "flushing"},
        {"name": "Long Island City", "slug": "long-island-city"}
    ],
    "los-angeles": [
        {"name": "Downtown LA", "slug": "downtown-los-angeles"},
        {"name": "Hollywood", "slug": "hollywood-ca"},
        {"name": "Beverly Hills", "slug": "beverly-hills"},
        {"name": "Santa Monica", "slug": "santa-monica"},
        {"name": "Venice", "slug": "venice-ca"},
        {"name": "Westwood", "slug": "westwood"},
        {"name": "Century City", "slug": "century-city"},
        {"name": "Bel Air", "slug": "bel-air"},
        {"name": "Brentwood", "slug": "brentwood-ca"},
        {"name": "Sherman Oaks", "slug": "sherman-oaks"},
        {"name": "Studio City", "slug": "studio-city"},
        {"name": "Encino", "slug": "encino"},
        {"name": "Van Nuys", "slug": "van-nuys"},
        {"name": "North Hollywood", "slug": "north-hollywood"},
        {"name": "Silver Lake", "slug": "silver-lake"},
        {"name": "Los Feliz", "slug": "los-feliz"},
        {"name": "Echo Park", "slug": "echo-park"},
        {"name": "Koreatown", "slug": "koreatown-la"},
        {"name": "West LA", "slug": "west-los-angeles"}
    ],
    "chicago": [
        {"name": "The Loop", "slug": "chicago-loop"},
        {"name": "River North", "slug": "river-north"},
        {"name": "Gold Coast", "slug": "gold-coast"},
        {"name": "Lincoln Park", "slug": "lincoln-park"},
        {"name": "Lakeview", "slug": "lakeview"},
        {"name": "Wicker Park", "slug": "wicker-park"},
        {"name": "Bucktown", "slug": "bucktown"},
        {"name": "Old Town", "slug": "old-town"},
        {"name": "West Loop", "slug": "west-loop"},
        {"name": "South Loop", "slug": "south-loop"},
        {"name": "Hyde Park", "slug": "hyde-park"},
        {"name": "Logan Square", "slug": "logan-square"},
        {"name": "Wrigleyville", "slug": "wrigleyville"},
        {"name": "Streeterville", "slug": "streeterville"},
        {"name": "Magnificent Mile", "slug": "magnificent-mile"}
    ],
    "boston": [
        {"name": "Back Bay", "slug": "back-bay"},
        {"name": "Beacon Hill", "slug": "beacon-hill"},
        {"name": "North End", "slug": "north-end"},
        {"name": "South End", "slug": "south-end"},
        {"name": "Financial District", "slug": "financial-district-boston"},
        {"name": "Seaport", "slug": "seaport"},
        {"name": "Fenway", "slug": "fenway"},
        {"name": "Allston", "slug": "allston"},
        {"name": "Brighton", "slug": "brighton"},
        {"name": "Brookline", "slug": "brookline"},
        {"name": "Cambridge", "slug": "cambridge"},
        {"name": "Somerville", "slug": "somerville"},
        {"name": "Charlestown", "slug": "charlestown"},
        {"name": "Jamaica Plain", "slug": "jamaica-plain"},
        {"name": "Roxbury", "slug": "roxbury"}
    ],
    "san-francisco": [
        {"name": "Financial District", "slug": "financial-district-sf"},
        {"name": "SoMa", "slug": "soma"},
        {"name": "Mission District", "slug": "mission-district"},
        {"name": "Castro", "slug": "castro"},
        {"name": "Haight-Ashbury", "slug": "haight-ashbury"},
        {"name": "Marina District", "slug": "marina-district"},
        {"name": "Pacific Heights", "slug": "pacific-heights"},
        {"name": "Nob Hill", "slug": "nob-hill"},
        {"name": "Russian Hill", "slug": "russian-hill"},
        {"name": "North Beach", "slug": "north-beach"},
        {"name": "Chinatown", "slug": "chinatown-sf"},
        {"name": "Potrero Hill", "slug": "potrero-hill"},
        {"name": "Hayes Valley", "slug": "hayes-valley"},
        {"name": "Sunset District", "slug": "sunset-district"},
        {"name": "Richmond District", "slug": "richmond-district"}
    ]
}

# Cross-border regions
CROSS_BORDER_REGIONS = [
    {
        "slug": "dc-maryland-virginia",
        "name": "DC-Maryland-Virginia",
        "description": "National Capital Region"
    },
    {
        "slug": "kansas-city-metro",
        "name": "Kansas City Metro",
        "description": "Kansas-Missouri Border Region"
    },
    {
        "slug": "cincinnati-tristate",
        "name": "Cincinnati Tri-State",
        "description": "Ohio-Kentucky-Indiana Region"
    },
    {
        "slug": "philadelphia-delaware-valley",
        "name": "Delaware Valley",
        "description": "PA-NJ-DE-MD Region"
    },
    {
        "slug": "portland-vancouver-metro",
        "name": "Portland-Vancouver Metro",
        "description": "Oregon-Washington Border"
    },
    {
        "slug": "quad-cities",
        "name": "Quad Cities",
        "description": "Illinois-Iowa Border"
    },
    {
        "slug": "memphis-metro",
        "name": "Memphis Metro",
        "description": "Tennessee-Arkansas-Mississippi"
    },
    {
        "slug": "charlotte-metro",
        "name": "Charlotte Metro",
        "description": "North Carolina-South Carolina"
    },
    {
        "slug": "st-louis-metro",
        "name": "St. Louis Metro",
        "description": "Missouri-Illinois Border"
    },
    {
        "slug": "augusta-metro",
        "name": "Augusta Metro",
        "description": "Georgia-South Carolina Border"
    }
]