# Generated by Django 4.2.11 on 2025-08-09 01:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('practice_area', models.CharField(choices=[('personal_injury', 'Personal Injury & Wrongful Death'), ('medical_malpractice', 'Medical Malpractice'), ('employment', 'Employment Litigation'), ('commercial', 'Commercial Disputes')], max_length=50)),
                ('background', models.TextField(help_text='Case background and context')),
                ('analysis', models.TextField(help_text='Economic analysis performed')),
                ('challenges', models.TextField(blank=True, help_text='Key challenges addressed')),
                ('outcome', models.TextField(blank=True, help_text='Case outcome or result')),
                ('amount', models.CharField(blank=True, help_text="Economic value (e.g., '$2.3M')", max_length=100)),
                ('featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('author', models.CharField(default='Chris Skerritt, Ph.D., CPA/ABV/CFF, CVA, MAFF', max_length=100)),
                ('content', models.TextField()),
                ('excerpt', models.TextField(blank=True, help_text='Brief description for listings', max_length=500)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('featured', models.BooleanField(default=False, help_text='Display on homepage')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('meta_description', models.CharField(blank=True, help_text='SEO meta description', max_length=160)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
            ],
            options={
                'ordering': ['-published_date'],
            },
        ),
    ]
