# Generated by Django 4.2.11 on 2025-08-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='Christopher Skerritt, M.Ed, MBA, CRC, LRC, FVE, IPEC, CVE, ABVE/F, REAS, CEAS I, CLCP, MSCC, CPRW, QRC', max_length=200),
        ),
    ]
