# Generated by Django 4.2.11 on 2025-08-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_update_existing_authors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casestudy',
            name='amount',
            field=models.CharField(blank=True, help_text='Economic value (e.g., $2.3M)', max_length=100),
        ),
    ]
