# Generated by Django 4.2.11 on 2025-08-09 01:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('case_type', models.CharField(choices=[('personal_injury', 'Personal Injury'), ('wrongful_death', 'Wrongful Death'), ('medical_malpractice', 'Medical Malpractice'), ('employment', 'Employment Litigation'), ('business_valuation', 'Business Valuation'), ('commercial_dispute', 'Commercial Dispute'), ('other', 'Other')], max_length=50)),
                ('jurisdiction', models.CharField(choices=[('state_court', 'State Court'), ('federal_court', 'Federal Court'), ('arbitration', 'Arbitration'), ('mediation', 'Mediation'), ('administrative', 'Administrative'), ('other', 'Other')], max_length=50)),
                ('timeline', models.CharField(choices=[('immediate', 'Immediate (< 30 days)'), ('soon', 'Soon (1-3 months)'), ('planning', 'Planning (3-6 months)'), ('future', 'Future (> 6 months)')], max_length=50)),
                ('case_details', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Internal notes')),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('display_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['display_order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, help_text="e.g., 'Managing Partner, Smith & Associates'", max_length=200)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['display_order', '-created_date'],
            },
        ),
    ]
